#!/bin/ksh
#
# set up base variables
# execute with dot
#
echo
echo $(date) $0 $* setbase begin
echo

echo
echo $(date) $0 set environment and experiment id
echo

echo envir=$envir

echo expid=${expid}

id=$(echo $expid|cut -c3-4)
echo id=$id

export STRICT="YES"

# For virtical structure
if [[ -d $SOURCEDIR/sorc/global-workflow.fd ]] ; then
    export HOMEDIR=$SOURCEDIR
fi

if [ -d /scratch2/NCEPDEV ]; then 
    echo "Using settings for Hera"
    export machine='HERA'
    
    export HOMEDIR=${HOMEDIR:-/scratch2/NCEPDEV/ensemble/noscrub/common/git/global_workflow/gefs_v12.1.0}
    export HOMERFC=/scratch2/NCEPDEV/ensemble/save/Walter.Kolczynski/ens_tracker
    export HOMEdata=/scratch2/NCEPDEV/ensemble/noscrub/common

    export COMROOThps=${HOMEdata}
    export COMROOTp1=/scratch2/NCEPDEV/rstprod/com 
    export PATH=$PATH:/scratch2/NCEPDEV/nwprod/NCEPLIBS/util/prod_util.v1.1.0/ush

    export GBBEPX_DATA_DIR_TODAY=$HOMEdata/GBBEPx
    export GBBEPX_DATA_DIR_YESTERDAY=$HOMEdata/GBBEPx
    export gbbepx_pattern='$GBBEPX_DATA_DIR/${local_name}.${day}.FV3.${CASE}Grid.${tiledir}.bin' # single-quotes required
    export gbbepx_days='$PDYm1' # single-quotes required
    export gbbepx_list="GBBEPx.bc GBBEPx.oc GBBEPx.so2 GBBEPx.pm25 meanFRP"
    export inout_list="BBURN3-bb,ebu_pm_10 SO4-bb,ebu_sulf plume,plumestuff GBBEPx.bc,ebu_bc GBBEPx.oc,ebu_oc GBBEPx.so2,ebu_so2 GBBEPx.pm25,ebu_pm_25 meanFRP,plumefrp"

elif [[ -d /gpfs/hps && -e /etc/SuSE-release ]] ; then
    echo "Using settings for WCOSS Cray"
    export machine='WCOSS_C'
    export JOBPHASE=
    export HOMEDIR=${HOMEDIR:-/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/common/git/global_workflow/gefs_v12.1.0}
    export HOMEtrak=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/common/git/ens_tracker/ens_tracker.v2.1.2
    export HOMEdata=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common
    export archsyndir=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/TCvitalData/syndat
    
elif [[ -L /usrx && "$( readlink /usrx 2> /dev/null )" =~ dell ]] ; then
    # We are on NOAA Venus or Mars
    echo "Using settings for WCOSS DELL Phase III"
    export machine='WCOSS_DELL_P3'
    export JOBPHASE=
    export HOMEDIR=${HOMEDIR:-/gpfs/dell6/emc/modeling/noscrub/Xianwu.Xue/gw_for_acorn/gw_for_gefs_v12.2.0_dell_p35}
    export HOMEtrak=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/ens_tracker.v2.1.2
    export archsyndir=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/TCvitalData/syndat
    export HOMEdata=/gpfs/hps2/nco/storage/fv3gefs/Bing.Fu/common
    #export HOMEdata=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common
    # export HOMEdata=/gpfs/dell2/emc/modeling/noscrub/Walter.Kolczynski/gefs_input
    # export COMINenkf_base=$HOMEdata/gfs_15/enkfgdas.
    # export COMINgfs_base=$HOMEdata/gfs_15/gfs.
    # export COMINcfs_base=$HOMEdata/cfs_2_sst/cfs.

    # export COMROOThps=${HOMEdata}
elif [[ -d /apps/prod ]]; then
    # We are on NOAA WCOSS2
    echo "Using settings for WCOSS2"
    export machine='WCOSS2'
    export JOBPHASE=
    export HOMEDIR=${HOMEDIR:-/lfs/h2/emc/ens/noscrub/emc.ens/common/git/gfs/gw_gefs_v12.2_bafca3b_Dec09_2021}
    export HOMEtrak=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/ens_tracker.v2.1.2
    export archsyndir=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/TCvitalData/syndat
    export HOMEdata=/gpfs/hps2/nco/storage/fv3gefs/Bing.Fu/common

fi

export basesource=$SOURCEDIR
export baseoutput=$WORKDIR

echo USER BASE DIRECTORY info:
echo SOURCE: $basesource
echo OUT: $baseoutput

echo
echo $(date) $0 $* setbase end
echo
