#!/bin/ksh
#
# set up base variables
# execute with dot
#
echo
echo `date` $0 $* setbase begin
echo

echo
echo `date` $0 set environment and experiment id
echo

#DHOU, 01/03/2013 add this block to generate the machine name related variables
#machl=`uname -n | cut -c1`

#if [[ $machl = r ]]; then
#  machl=f
#fi
#if [[ $machl = n ]]; then
#  machl=l
#fi

echo envir=$envir

echo expid=${expid}

id=`echo $expid|cut -c3-4`
echo id=$id

#echo
#echo USER to prescribe user ID and JOB queue infirmation
#echo
#PROJECT=ensemble
#LOGNAME=$LOGNAME
#SUBNAME=
#JOBPRIO=      
#JOBQUEUE=dev
#JOBPHASE=
#Please make sure you have the correct account information
#export account=GEN-T2O

#if [[ "$LOGNAME" = "emc.enspara" || "$LOGNAME" = "emc.enspara1" ]]; then
#    SUBNAME=/XX    #members of the enspara/enspara1 group accounts need to define e.g SUBNAME=/dc
#    JOBPRIO=high       #(default; it could be high/max)
#fi

#echo USER info: $PROJECT $LOGNAME $SUBNAME $JOBPRIO

#echo JOB QUEUE info prescribed: $JOBQUEUE $JOBPHASE $JOBPRIO

#echo ACCOUNT info: $account

#echo
#echo `date` $0 set ROOT directory tree locations
#echo

# For virtical structure
if [[ -d $SOURCEDIR/sorc/global-workflow.fd ]] ; then
    export HOMEDIR=$SOURCEDIR
fi

if [ -d /scratch2/NCEPDEV ]; then 
    echo "Using settings for Hera"
    export machine='HERA'
    
    export HOMEDIR=${HOMEDIR:-/scratch2/NCEPDEV/ensemble/noscrub/common/git/fv3gfs/lgan_fv3_ww3_fb95cd3c_20191105}
    export HOMERFC=/scratch2/NCEPDEV/ensemble/save/Walter.Kolczynski/ens_tracker
    export HOMEdata=/scratch2/NCEPDEV/ensemble/noscrub/common

    # export HOMEdata=/scratch2/NCEPDEV/ensemble/noscrub/Walter.Kolczynski/gefs_input
    # export COMINenkf_base=$HOMEdata/gfs_15/enkfgdas.
    # export COMINgfs_base=$HOMEdata/gfs_15/gfs.
    # export COMINcfs_base=$HOMEdata/cfs_2_sst/cfs.

    export COMROOThps=${HOMEdata}
    export COMROOTp1=/scratch2/NCEPDEV/rstprod/com 
    export PATH=$PATH:/scratch2/NCEPDEV/nwprod/NCEPLIBS/utils/prod_util.v1.1.0/ush

elif [[ -d /dcom && -d /hwrf ]] ; then
    echo "Using settings for WCOSS Phase II"
    export machine='WCOSS'
    export JOBPHASE=2
    export HOMEDIR=${HOMEDIR:-/ensemble/save/Walter.Kolczynski/global-workflow/fv3gefs_f0b283bd_20190517}
    export HOMEtrak=/gpfs/hps3/emc/ensemble/save/emc.enspara/RFC/ens_tracker.v1.1.8 # Outdated version    
    export HOMEdata=/ensemble/noscrub/Walter.Kolczynski/gefs_input/gfs_15_para
    export COMINenkf_base=$HOMEdata/enkf.gdas.
    export COMINgfs_base=$HOMEdata/gfs.
    export COMINcfs_base=/ensemble/noscrub/Walter.Kolczynski/gefs_input/cfs_2_sst/cfs.

    export CHGRESEXEC=$HOMEDIR/exec/chgres_recenter.exe

elif [[ -d /gpfs/hps && -e /etc/SuSE-release ]] ; then
    echo "Using settings for WCOSS Cray"
    export machine='WCOSS_C'
    export JOBPHASE=
    export HOMEDIR=${HOMEDIR:-/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/common/git/fv3gfs/lgan_fv3_ww3_fb95cd3c_20191105_newfv3upp}
    export HOMEtrak=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/common/git/ens_tracker/ens_tracker.v2.1.2
    export HOMEdata=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common
    export archsyndir=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/TCvitalData/syndat
    
elif [[ -L /usrx && "$( readlink /usrx 2> /dev/null )" =~ dell ]] ; then
    # We are on NOAA Venus or Mars
    echo "Using settings for WCOSS DELL Phase III"
    export machine='WCOSS_DELL_P3'
    export JOBPHASE=
    export HOMEDIR=${HOMEDIR:-/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/fv3gfs/lgan_fv3_ww3_fb95cd3c_20191105_newfv3upp}
    export HOMEtrak=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/ens_tracker.v2.1.2
    export HOMEdata=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common
    export archsyndir=/gpfs/dell2/emc/verification/noscrub/emc.enspara/common/git/ens_tracker/TCvitalData/syndat

    #export HOMEdata=/gpfs/dell2/emc/modeling/noscrub/Walter.Kolczynski/gefs_input
    #export COMINenkf_base=$HOMEdata/gfs_15/enkfgdas.
    #export COMINgfs_base=$HOMEdata/gfs_15/gfs.
    #export COMINcfs_base=$HOMEdata/cfs_2_sst/cfs.

fi


#export JOBQUEUE=$JOBQUEUE$JOBPRIO$JOBPHASE
#echo JOB QUEUE info: $JOBQUEUE 

#echo ROOT DIRECTORY info:
#echo $machine  jobqueue=$JOBQUEUE
#echo homedir: $HOMEDIR

#echo
#echo `date` $0 set user base directory tree locations
#echo

export basesource=$SOURCEDIR
export baseoutput=$WORKDIR

echo USER BASE DIRECTORY info:
echo SOURCE: $basesource
echo OUT: $baseoutput

echo
echo `date` $0 $* setbase end
echo
