#!/bin/ksh 

echo $(date) $0 $(date -u) begin

set -xa
export PS4='$SECONDS + '
date

export total_tasks=${total_tasks:-1}
export gefsmpexec=${gefsmpexec:-"mpirun -n $total_tasks"}
export APRUN=${gefsmpexec:-"mpirun -n $total_tasks"}

####################################
# Load the grib module
####################################
export CNVGRIB=$CNVGRIB

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}

mkdir -p $DATA
cd $DATA

######################################
# Set up the cycle variable
######################################
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gefs}
export RUN=cqpf

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# SENDECF  - Flag Events on ECF
# VERBOSE  - Specify Verbose Output
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}

export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export UTILgefs=${UTILgefs:-$HOMEgefs/util}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMROOT}/${NET}/${envir}
export COMOUT=$COMROOT/${NET}/${envir}/gefs.${PDY}/${cyc}/atmos/ensstat
export COMINshef=${COMINshef:-${DCOMROOT}/prod/shef_pefiles}
export COMINstat=${COMINstat:-$COMIN}

mkdir -m 775 -p $COMOUT

msg="HAS BEGUN on $(hostname)"
postmsg "$jlogfile" "$msg"

env | sort

#############################################################
# Execute the script
if (( cyc == 00 )); then
    $HOMEgefs/scripts/exglobal_enscqpf.sh.ecf
    err=$?
	echo $err
else
    echo "skip cqpf processing in development for cyc=$cyc"
fi
#############################################################

if [ ${err:-0} = 0 ]; then
    msg="$job completed normally!"
else
    msg="FATAL ERROR: $job failed!"
fi
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

echo "$(date) $0 $(date -u) end"

exit $err
