#!/bin/ksh 

echo `date` $0 `date -u` begin
set -xa
export PS4='$SECONDS + '

####################################

# 01/28/2013 New variables added for WCOSS and cross-machine unfication
export gefsmachine=${gefsmachine:-wcoss}
export gefsmpexec=${gefsmpexec:-mpirun.lsf}

####################################
# obtain unique process id (pid) and identify working directory
####################################
export pid=$$

if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
export DATA=$DATAROOT/gefs_legacy_init_$cyc.$envir.save
else
  echo basenfs=$basenfs
  echo baseptmp=$baseptmp
  echo basetmp=$basetmp
  export DATA=$basetmp/tmpnwprd1/gefs_legacy_init_$PDY$cyc.$envir.save
echo DATA=$DATA
fi
cd $DATA

export cycle=t${cyc}z
export cycle_fcst=t${cyc_fcst}z

echo cyc=$cyc cyc_fcst=$cyc_fcst
echo cycle=$cycle cycle_fcst=$cycle_fcst

if (( cyc == cyc_fcst )); then
  export cycsuffix=false
  export fcstlong=true
else
  export fcstlong=false
  export cycsuffix=true
fi

echo fcstlong=$fcstlong
echo cycsuffix=$cycsuffix

####################################
# Specify NET and RUN Name and model
####################################
export NET=gens
export RUN=enstr

####################################
# File To Log Msgs
####################################
if [[ $envir = prod ]]; then
  export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
elif [[ $envir = para ]] || \
     [[ $envir = test ]]; then
  export jlogfile=/com/logs/${envir}/jlogfile
else
  export jlogfile=$baselog/com/logs/jlogfile
fi

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# RMGES    - Clean Files in $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SAVEGES=YES
export SENDECF=YES
export SENDCOM=YES
export RERUN=NO
export VERBOSE=YES

if [ $cyc -eq 00 ]; then
  if [[ $envir = prod ]]; then
    export SENDDBN=NO
  else
    export SENDDBN=NO
  fi
else
  export SENDDBN=NO
fi

 
####################################
# Specify Execution Areas
####################################

if [[ $envir = prod ]] || [[ $envir = para ]] || [[ $envir = test ]]; then
  export HOMEGLOBAL=/nw${envir}/gefs_legacy.${gefs_legacy_ver}
fi
if [[ $envir = dev ]]; then
  # RLW 20141008 modify to obtain and use version for vertical structure
  . $basesource/nw$envir/*/versions/gefs_legacy.ver
  export HOMEGLOBAL=$basesource/nw$envir/gefs_legacy.${gefs_legacy_ver}
fi
export EXECGLOBAL=$HOMEGLOBAL/exec
export FIXGLOBAL=$HOMEGLOBAL/fix
export PARMGLOBAL=$HOMEGLOBAL/parm
export USHGLOBAL=$HOMEGLOBAL/ush
if [[ $envir = dev ]]; then
  export FIXGLOBAL=/nwprod/fix
fi

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################################
echo set parameters using gefs.parm
##############################################
if [[ $envir = prod ]]; then
. $PARMGLOBAL/gefs.parm
. $PARMGLOBAL/gefs_init.parm
elif [[ $envir = para ]] || \
     [[ $envir = test ]]; then
  # RLW 20141008 modify to obtain and use version for vertical structure
. $PARMGLOBAL/gefs.parm
. $PARMGLOBAL/gefs_init.parm
else
  # RLW 20141008 modify to obtain and use version for vertical structure
. $basesource/nw$envir/gefs_legacy.${gefs_legacy_ver}/parm/gefs.parm
. $basesource/nw$envir/gefs_legacy.${gefs_legacy_ver}/parm/gefs_init.parm
fi

echo
env | sort
echo

##############################
# Set up the UTILITIES
##############################
export utilscript=/nwprod/util/ush

##############################
# Run setup to initialize working directory and utility scripts
##############################
sh $utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
sh $utilscript/setpdy.sh
if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
. PDY
else
  echo PDY=$PDY is already set
fi

##############################################
# for global_chgres.sh
##############################################
export SLMASK=/dev/null

##############################################
# Define COM directories
##############################################
if [[ $envir = prod ]]; then
  export GFSCOMIN=/com/gfs/${envir}/gfs.$PDY
elif [[ $envir = para ]] || [[ $envir = test ]]; then
  gfssource=prod
  if [[ "$gfssource" = para ]]; then
    export GFSCOMIN=/com/gfs/para/gfs.$PDY
  else
    export GFSCOMIN=/com/gfs/prod/gfs.$PDY
  fi
else
  if [[ "$gfssource" = para ]]; then
    export GFSCOMIN=/com/gfs/para/gfs.$PDY
  elif [[ "$gfssource" = prod ]]; then
    export GFSCOMIN=/com/gfs/prod/gfs.$PDY
  else
    export GFSCOMIN=$baseptmp/com/gfs/${envir}/gfs.$PDY
  fi
fi

if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
  export COMIN=/com/${NET}/${envir}/gefs_legacy.${PDY}
  export COM=/com/${NET}/${envir}
  export COMINm1=/com/${NET}/${envir}/gefs_legacy.${PDYm1}
  export COMINm2=/com/${NET}/${envir}/gefs_legacy.${PDYm2}
  export COMINm3=/com/${NET}/${envir}/gefs_legacy.${PDYm3}
  export COMINm4=/com/${NET}/${envir}/gefs_legacy.${PDYm4}
else
  export COMIN=$baseoutput/com/${NET}/${envir}/gefs_legacy.${PDY}
  export COM=$baseoutput/com/${NET}/${envir}
  export COMINm1=$baseoutput/com/${NET}/${envir}/gefs_legacy.${PDYm1}
  export COMINm2=$baseoutput/com/${NET}/${envir}/gefs_legacy.${PDYm2}
  export COMINm3=$baseoutput/com/${NET}/${envir}/gefs_legacy.${PDYm3}
  export COMINm4=$baseoutput/com/${NET}/${envir}/gefs_legacy.${PDYm4}
fi

if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
  export COMOUT=/com/${NET}/${envir}/gefs_legacy.${PDY}
else
  export COMOUT=$baseoutput/com/${NET}/${envir}/gefs_legacy.${PDY}
fi

mkdir -m 775 -p $COMOUT/$cyc/init
mkdir -m 775 -p $COMOUT/$cyc/sflux

##############################################
# Define GES directories
##############################################
if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
  gespath=/nwges/${envir}
else
  gespath=$baseoutput/nwges/${envir}
fi
export GESdir=$gespath/gefs_legacy.${PDY}
mkdir -m 775 -p $GESdir

##############################################
echo list environment before running script
##############################################

echo
env | sort
echo

#############################################################
# Execute the script
if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
  # RLW 20141008 modify to obtain and use version for vertical structure
  /nw${envir}/gefs_legacy.${gefs_legacy_ver}/scripts/exgefs_init_et.sh.ecf
else
  # RLW 20141008 modify to obtain and use version for vertical structure
  $basesource/nw${envir}/gefs_legacy.${gefs_legacy_ver}/scripts/exgefs_init_et.sh.ecf
fi
#############################################################

cat $pgmout

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Save the working directory
# for the COMBINE job
##############################

echo `date` $0 `date -u` end
