#!/bin/ksh 
#####################################################################
# 1/7/2014, Jiayi Peng and Dingchen Hou   Scripts are modified to be vertical structure 
#################################################################### 
##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. PDY
#echo $PDY

export date=2016032600
#export date=${PDY}00

#export date=${PDY}06
yyyymmdd=`echo $date | cut -c1-8`
echo $date,$yyyymmdd
#echo `date` $0 `date -u` begin

set -xa
export PS4=' + $SECONDS $na $LINENO: '
echo $date

export gefsmpexec=${gefsmpexec:-mpirun.lsf}

export APRUN=${gefsmpexec_mpmd:-mpirun.lsf}
#export APRUNTRACK="aprun -j1 -n21 -N7 -d1"
#export NODES=3
#export IOBUF_PARAMS="*:size=32M:count=4:verbose"

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

#export pid=$$
#export DATAacc=/gpfs/hps3/ptmp/${LOGNAME}/acc
##export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
#mkdir -p $DATAacc
#cd $DATAacc

export COMOUT=$COMROOT/${NET}/${envir}/gefs.${yyyymmdd}/00

############################
# Set up cycle varaible
############################
cyc=`echo $date | cut -c9-10`
export cycle=t${cyc}z
export cycle_fcst=t${cyc}z

echo cyc=$cyc cyc_fcst=$cyc_fcst
echo cycle=$cycle cycle_fcst=$cycle_fcst

if (( cyc == cyc_fcst )); then
	export fcstlong=true
	export cfsuffix=""
	export cycsuffix=false
else
	export fcstlong=false
	export cfsuffix=".cycfs$cyc_fcst"
	export cycsuffix=true
fi # (( cyc == cyc_fcst ))

export fcstlong
echo fcstlong=$fcstlong

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
echo $outid,$jobid,$pgmout,$pgmerr

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
#export HOMEgefs=/gpfs/hps3/emc/ensemble/save/Hong.Guan/acc
#export HOMEacc=/gpfs/hps3/emc/ensemble/save/Hong.Guan/acc

export EXECacc=${EXECacc:-$HOMEgefs/exec}
export SORCacc=${SORCacc:-$HOMEgefs/sorc/gefs_postacc.fd}
#export USHens_acc=${HOMEacc:-$HOMEacc/ush}
export USHens_acc=$HOMEgefs/ush
export FIXens_acc=${FIXacc:-$HOMEgefs/fix}
#export SCRIPTSens_acc=${SCRIPTSens_acc:-$HOMEacc/scripts}

export PARMgefs=$HOMEgefs/rocoto/parm
echo $PARMgefs

##############################
# Run setup to initialize working directory and utility scripts
##############################
#ksh setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY
echo $PDY
#export PDY=20140913 

##############################################
# Define COM directories
##############################################
##export COMINgfs=${COMINgfs:-${COMROOThps}/gfs/prod/gfs.${PDY}}
##export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}

#export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/gefs.${PDY}/${cyc}}
#export COMIN_00and03=/gpfs/dell2/emc/verification/noscrub/emc.enspara/$LOGNAME/post_dat1/sfcsig
export COMIN_00and03=/gpfs/dell3/nco/storage/fv3gefs/Hong.Guan/${yyyymmdd}06
export COMIN_master=$COMOUT/master
#/$RUNMEM.$cycle.master.grb2f$fhr$cfsuffix
#export COMIN_06=/gpfs/hps3/emc/ensemble/noscrub/$LOGNAME/master_reforecast/master
#export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}/acc}

#export ensdira=$COMIN/pgrb2ap25
#export ensdirb=$COMIN/pgrb2bp25
##############################################
echo set parameters using gefs.parm
##############################################
. $PARMgefs/gefs_dev.parm

if [[ $envir = dev ]]; then
	export fhmax=$fhmax00
elif (( cyc == 06 )); then
	export fhmax=$fhmax06
elif (( cyc == 12 )); then
	export fhmax=$fhmax12
elif (( cyc == 18 )); then
	export fhmax=$fhmax18
fi

####################################
# Create member list
####################################

if [[ $fcstlong = true ]]; then
	memberlist="c00"
else
	memberlist=""
fi

(( imem = 0 ))
while (( imem < npair * 2 )); do
	(( imem = imem + 1 ))
	if (( imem < 10 )); then
		imem=0$imem
	fi
	memberlist="$memberlist p$imem"
done # while (( imem < npair * 2 ))
echo memberlist=$memberlist

#export homesyndir=$HOMEacc

echo
env | sort
echo

########################################################
# Execute the acc script.
export cmodel=ens
#export loopnum=1
export ymdh=${date}

#-----------input data checking -----------------
##${USHens_tracker}/data_check.sh
#------------------------------------------------
msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

$USHens_acc/fv3gefsrf_0306acc.sh ${ymdh} ${DATA} > fv3gefsrf_0306acc.${cmodel}.${ymdh}.out

#/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/Hong.Guan/reforecast_19Y_acc/ush/fv3gefsrf_0306acc.sh ${ymdh} ${DATA} > fv3gefsrf_0306acc.${cmodel}.${ymdh}.out
#${USHens_acc}/fv3gefsrf_writef0306.sh ${ymdh} ${DATAacc} > writef0306.${cmodel}.${ymdh}.out



################################
msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

#cat $pgmout

exit

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
	cd $DATAROOT
	rm -rf $DATA
fi

echo `date` $job completed
