#!/bin/sh

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date
export MODEL_OUT_FORM=binarynemsiompiio

export total_tasks=${total_tasks:-10}
export gefsmpexec=${gefsmpexec:-"mpirun -n $total_tasks"}
export APRUN_POSTSND=${gefsmpexec:-'mpirun -n $total_tasks'}
export APRUN_POSTSNDCFP=${gefsmpexec_mpmd:-'mpirun -n $total_tasks cfp'}

########################################
# Runs GFS BUFR SOUNDINGS
########################################

############################
export MP_EUIDEVELOP=min
export KMP_STACKSIZE=2048m
export MPICH_ALLTOALL_THROTTLE=0
export MP_SINGLE_THREAD=yes
export MP_EAGER_LIMIT=65536
export MP_USE_BULK_XFER=no
export MP_COLLECTIVE_OFFLOAD=no
export MP_SHARED_MEMORY=yes
export MP_MPILIB=mpich2
export MP_LABELIO=yes

####################################
# obtain unique process id (pid) and make temp directory
###################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir -p $DATA
cd $DATA

# Define MASTERRES for master file grid, default being Gaussian with alternatives of  p125/p25/p5
export mem=`echo $RUNMEM|cut -c3-5`

######################################
# Set up the cycle variable
######################################
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}
export model=${model:-gfs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# SENDECF  - Flag Events on ECF
# VERBOSE  - Specify Verbose Output
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export VERBOSE=${VERBOSE:-YES}

# Specify Execution Areas
export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export HOMEpost=${HOMEpost:-${HOMEgefs}}

export HOMEgfs=${HOMEgfs:-$HOMEgefs}

###################################
# Set up the UTILITIES
###################################

export HOMEbufrsnd=${HOMEgfs:-$HOMEgefs}
export EXECbufrsnd=${EXECgfs:-$HOMEgfs/exec}
export FIXbufrsnd=${FIXgfs:-$HOMEgfs/fix/product}
export PARMbufrsnd=${PARMgfs:-$HOMEgfs/parm/product}
export USHbufrsnd=${USHgfs:-$HOMEgfs/ush}
export SCRbufrsnd=${SCRgfs:-$HOMEgfs/scripts}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

##############################
# Define COM Directories
##############################
export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}}
export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}}
export pcom=${pcom:-${COMOUT}/wmo}
export COMAWP=${COMAWP:-${COMOUT}/gempak}
mkdir -p $COMOUT $pcom $COMAWP

if [ -e $COMOUT/bufr/$mem ]; then
    rm -rf $COMOUT/bufr/$mem
fi
mkdir -m 775 -p $COMOUT/bufr/$mem
mkdir -m 775 -p $COMOUT/misc/bufr

############################################
# Run gefs.parm to get input variables
############################################
. $PARMgefs/gefs.parm

export FHMAX_HF=$FHMAXHF
export FHOUT_HF=$FHOUTHF
export FHOUT=$FHOUTLF

export JCAP=${JCAPFV:-766}
export LEVS=${LEVSHR:-64}
export LATB=${LATBFV:-768}
export LONB=${LONBFV:-1536}

export STARTHOUR=${STARTHOUR:-00}
export ENDHOUR=${ENDHOUR:-180}
export NINT3=$FHOUTLF     ##second period time interval
export NZERO=6
export NEND1=${NEND1:-180} #${FHMAXHF}   ##first period length with time interval = NINT1
export NINT1=$FHOUTHF 

if (( fhmax <= ENDHOUR )); then
        export ENDHOUR=$fhmax
fi
if (( NEND1 >= ENDHOUR )); then
        export NEND1=$ENDHOUR
fi

export INCREMENT=12
export OUTFILE=meteomrf
export MAKEBUFR=NO
export F00FLAG=YES

env

########################################################
# Execute the script.
$HOMEgefs/scripts/exgefs_postsnd.sh.ecf
########################################################

if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
