#!/bin/ksh 
#####################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
######################################################################

#$SMSBIN/smsinit $LOADL_STEP_ID 
echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '

# 01/28/2013 New variables added for WCOSS and cross-machine unfication
export gefsmachine=${gefsmachine:-wcoss}
export gefsmpexec=${gefsmpexec:-mpirun.lsf}
export machine=${gefsmachine:-wcoss}

export GRIBVERSION=${GRIBVERSION:-grib2}

###########################################
# Run gefs_config to get input parameters
###########################################
if [ "$RUN_ENVIR" = dev ]      ### For Developers
then
  . $basesource/nwdev/parm/gefs_config
# . $basesource/nwdev/parm/gefs_config_old
else
  VERSION_FILE=/nw{$envir}/versions/gefs.ver
  if [-f $VERSION_FILE]; then
     . $VERSION_FILE
  else
     ecflow_client --abort
     exit
  fi
fi

export HOMEgefs=${HOMEGEFS}
export HOMEutil=${HOMEUTIL:-/nwprod/util}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
if [ "$RUN_ENVIR" = dev ]    ### For Developers
then
   export DATA_IN=${DATA_IN:-$basetmp/tmpnwprd}
else                       ### For Operations
   export DATA_IN=/tmpnwprd
fi

export DATA=$DATA_IN/cqpd.${pid}

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=gens
export RUN=stat

####################################
# File To Log Msgs
####################################
if [ "$RUN_ENVIR" = dev ]     ### For Developers
then
   export jlogfile=${jlogfile:-$baselog/com/logs/jlogfile}
else                        ### For Operations
   export jlogfile=/com/logs/para/jlogfile
fi

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
  export SENDCOM=${SENDCOM:-YES}
  export SENDDBN=${SENDDBN:-NO}
  export SENDSMS=${SENDSMS:-YES}
  export SENDDBN_GB2=${SENDDBN_GB2:-NO}

  # Specify Execution Areas
# export HOMEGLOBAL=$basesource/nw${envir}
else                             ### For Operations
  export SENDCOM=YES
  export SENDDBN=YES
  export SENDSMS=YES
  export SENDDBN_GB2=YES

  # Specify Execution Areas
# export HOMEGLOBAL=/nwprod
fi

  export HOMEgefs=$HOMEGEFS
  export EXECgefs=$HOMEgefs/exec
  export USHgefs=$HOMEgefs/ush
  export FIXgefs=$HOMEgefs/fix
  export PARMgefs=$HOMEgefs/parm


export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Set up the UTILITIES
##############################
export utilscript=$HOMEutil/ush
export EXECutil=$HOMEutil/exec
export FIXutil=$HOMEutil/fix
#export GRBINDEX=/nwprod/util/exec/grbindex

##############################
# Run setup to initialize working directory and utility scripts
##############################
sh $utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
sh $utilscript/setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMINGEST=$TMPCOM/ingest/prod
export COMINGEST=/ensemble/noscrub/Yan.Luo/com-ingest-prod
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
  export COM_IN=${COM_IN:-${baseoutput}/com/${NET}/${envir}}
  export COM_OUT=${COM_OUT:-${baseoutput}/com/${NET}/${envir}}
  export COM_IN=/ensemble/noscrub/emc.enspara/xz/T574L64SL/EK0
# export COM_OUT=${COM_OUT:-/ptmpp1/${LOGNAME}/com/${NET}/${RUN_ENVIR}}

  export COMIN=$COM_IN
  export COMOUT=$COM_OUT/gefs.${PDY}/${cyc}/ensstat
else                              ### For Operations
  export COMIN=/com/${NET}/${envir}
  export COMOUT=/com/${NET}/${envir}/gefs.${PDY}/${cyc}/ensstat
fi

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
# Execute the script
if (( cyc == 00 )); then
 $HOMEgefs/scripts/exglobal_enscqpf.sh.ecf
else
 echo skip cqpf processing in development for cyc=$cyc
fi

#if [[ $envir = prod ]] || \
#   [[ $envir = para ]] || \
#   [[ $envir = test ]]; then
#/nw${envir}/scripts/exglobal_enscqpf.sh.sms
#else
#if (( cyc == 00 )); then
#$basesource/nw${envir}/scripts/exglobal_enscqpf.sh.sms
#else
#echo skip cqpf processing in development for cyc=$cyc
#fi
#fi

#############################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"


##############################
# Remove the Temporary working directory
##############################
#cd $DATA_IN
#rm -rf $DATA

$SMSBIN/endt
