#!/bin/ksh 

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date
############################
# Set up cycle varaible
############################
 export cycle=t${cyc}z
 export cycle_fcst=t${cyc_fcst}z


# if (( cyc == cyc_fcst )); then
#       export cycsuffix=false
#       export fcstlong=true
# else
#       export fcstlong=false
#       export cycsuffix=true
# fi


####################################
# obtain unique process id (pid) and make working directory
####################################
export pid=$$
export DATA=$DATAROOT/gefs_init_$PDY$cyc.$envir.save

echo DATA=$DATA
if [[ -d $DATA ]]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA


##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

 
####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export EXECgefs=${EXECgefs:-$HOMEgefs/exec}

##############################################
echo set parameters using gefs.parm
##############################################
#. $PARMgefs/gefs.parm
#. $PARMgefs/gefs_init.parm

##############################################
# Define COM directories
##############################################

#if [[ $gfssource != prod ]]; then
#	export COMINgfs=${COMINgfs_base}${PDY}/$cyc
#	export COMINenkf=${COMINenkf_base}
#fi
#export COMINgfs=${COMINgfs:-${COMROOThps}/gfs/prod/gfs.${PDY}/$cyc}
#export COMINenkf=${COMINenkf:-${COMROOThps}/gfs/prod/enkf.gdas.}

export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

#export pdycycp=`$NDATE -$fhrp $PDY$cyc`
#export pdyp=`echo $pdycycp|cut -c1-8`
#export cycp=`echo $pdycycp|cut -c9-10`

mkdir -m 775 -p $COMOUT/$cyc/init

##############################################
# Define GES directories
##############################################
export GESOUT=${GESOUT:-$GESROOT/${envir}}
export GESOUT=$GESOUT/gefs.${PDY}
mkdir -m 775 -p $GESOUT

##############################################
echo locations of scripts and executables
##############################################
#echo location of Get CFS SST
#export GEFS_ANOM2_FCST=${EXECgefs}/gefs_anom2_fcst
#export GEFS_NSTGEN=${EXECgefs}/gefs_nstgen

##############################################
echo list environment before running script
##############################################

env | sort

#############################################################
# Execute the script
$HOMEgefs/scripts/exgefs_getcfssst.sh.ecf
#############################################################
ERR=$?

echo $ERR

if [ $ERR = 0 ]; then
    msg="JOB COMPLETED NORMALLY"
else
    msg="JOB FAILED!"
fi

postmsg "$jlogfile" "$msg"

##############################
# Save the working directory
# for the ET and COMBINE jobs
##############################

echo `date` $0 `date -u` end

exit $ERR
