#!/bin/ksh 

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

export APRUN=${gefsmpexec_mpmd:-mpirun.lsf}

############################
# Set up cycle varaible
############################
 export cycle=t${cyc}z

####################################
# obtain unique process id (pid) and make working directory
####################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}

echo DATA=$DATA
if [[ -d $DATA ]]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# Specify Execution Areas
####################################
 export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
#export HOMEgsm=${HOMEgsm:-$NWROOT/gsm.${gsm_ver}}
#export HOMEenkf=${HOMEenkf:-$NWROOTp2/enkf.${enkf_ver}}

#export EXECgsm=${EXECgsm:-$HOMEgsm/exec}
#export USHgsm=${USHgsm:-$HOMEgsm/ush}
#export UTILgefs=${UTILgefs:-$HOMEgefs/util}
#export FIXgsm=${FIXgsm:-$HOMEgsm/fix/fix_am}
#export PARMgsm=${PARMgsm:-$HOMEgsm/parm}

#export FIXGLOBAL=$FIXgsm

#export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
#export USHgefs=${USHgefs:-$HOMEgefs/ush}
#export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
 export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

##############################################
echo set parameters using gefs.parm
##############################################
. $PARMgefs/gefs.parm
. $PARMgefs/gefs_init.parm

### echo Looking  the earlier EnKF  
#cycles from fhrpstart back to fhrpend  (hr)
export fhrpstart=$fhrp
export fhrpend=96
 
env | sort

##############################################
# Define COM directories
##############################################
if [[ $gfssource != prod ]]; then
	export COMINgfs=${COMINgfs_base}${PDY}/$cyc
	export COMINenkf=${COMINenkf_base}
fi

export COMINgfs=${COMINgfs:-${COMROOThps}/gfs/prod/gfs.${PDY}/$cyc}
export COMINenkf=${COMINenkf:-${COMROOThps}/gfs/prod/enkf.gdas.}

#export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
#export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

#export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
#export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

export COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}

export pdycycp=`$NDATE -$fhrp $PDY$cyc`
export pdyp=`echo $pdycycp|cut -c1-8`
export cycp=`echo $pdycycp|cut -c9-10`

mkdir -m 775 -p $COMOUT/$cyc/init

##############################################
# Define GES directories
##############################################
export GESOUT=${GESOUT:-$GESROOT/${envir}}
export GESOUT=$GESOUT/gefs.${PDY}
mkdir -m 775 -p $GESOUT

##############################################
echo locations of scripts and executables
##############################################
#echo location of EnKF utility executable
#export XC=.x
#export GETATMENSMEANEXEC=${GETATMENSMEANEXEC:-${HOMEgsm}/exec/getsigensmeanp_smooth$XC}
#export RECENATMEXEC=${RECENATMEXEC:-${HOMEgsm}/exec/recentersigp$XC}

#echo location of nemsioget
#export nemsioget=$nemsioget
#export nemsioget=$EXECgsm/nemsio_get
#echo location of chgres script and executable
#export CHGRESTHREAD=$NTHREADS_SIGCHGRS
# Change Resolution script and executable

#export chgresush=$USHgsm/global_chgres.sh
#export CHGRESEXEC=$EXECgsm/global_chgres
#export CHGRESEXEC=$HOMEgsm/exec/chgres_recenter.exe

##############################################
echo list environment before running script
##############################################

env | sort

#############################################################
# Execute the script
$HOMEgefs/scripts/exgefs_init_recenter.sh.ecf
#############################################################

cat $pgmout

#We should check error message here  ---- Dingchen
msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT

if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

echo `date` $0 `date -u` end
