#!/bin/ksh 

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

###########################################
# Run gefs_config_dev to get input parameters
###########################################

if [ "$RUN_ENVIR" = dev ]   ### For Developers
then
  . $basesource/nwdev/parm/gefs_config_dev
fi

export APRUN=${gefsmpexec:-mpirun}

############################
# Set up cycle varaible
############################

export cycle=t${cyc}z
export cycle_fcst=t${cyc_fcst}z

if (( cyc == cyc_fcst )); then
  export cycsuffix=false
  export fcstlong=true
else
  export fcstlong=false
  export cycsuffix=true
fi

####################################
# obtain unique process id (pid) and make temporary working directory
####################################
export pid=$$
export DATATEMP=$DATAROOT/${job}.${pid}.temp

echo DATATEMP=$DATATEMP
if [[ -d $DATATEMP ]]; then
  rm -rf $DATATEMP
fi
mkdir -p $DATATEMP
cd $DATATEMP

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

rm -rf $DATATEMP

####################################
# identify saved working directory
####################################
export DATA=$DATAROOT/gefs_init_$PDY$cyc.$envir.save
cd $DATA

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

 
####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export HOMEgsm=${HOMEgsm:-$NWROOT/gsm.${gsm_ver}}
export HOMEenkf=${HOMEenkf:-$NWROOTp1/enkf.${enkf_ver}}

export EXECgsm=${EXECgsm:-$HOMEgsm/exec}
export USHgsm=${USHgsm:-$HOMEgsm/ush}
export FIXgsm=${FIXgsm:-$HOMEgsm/fix/fix_am}
export PARMgsm=${PARMgsm:-$HOMEgsm/parm}

export EXECGLOBAL=${EXECgsm:-$HOMEgsm/exec}
export USHGLOBAL=${USHgsm:-$HOMEgsm/ush}
export FIXGLOBAL=${FIXgsm:-$HOMEgsm/fix/fix_am}

export EXECgefs=${EXECgefs:-$HOMEGgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

##############################################
echo set parameters using gefs.parm
##############################################

. $PARMgefs/gefs.parm
. $PARMgefs/gefs_init.parm

env | sort

##############################################
# for global_chgres.sh
##############################################
export SLMASK=/dev/null

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

#####
  export XC=.x
export GETATMENSMEANEXEC=${GETATMENSMEANEXEC:-${HOMEenkf}/exec/getsigensmeanp_smooth$XC}
export RECENATMPEXEC=${RECENATMPEXEC:-${HOMEenkf}/exec/recentersigp$XC}


##############################################
echo list environment before running script
##############################################

env | sort

#############################################################
# Execute the script
#############################################################
$HOMEgefs/scripts/exgefs_init_process.sh.ecf

cat $pgmout

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Save the working directory
# for the COMBINE job
##############################
