#!/bin/sh

########################################
# Creates GEFS META files for NAWIPS
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATAROOT}/${job}.${pid}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${COMROOT}/logs/jlogfiles/jlogfile.${job}.$$

#############################################
#set the fcst hrs for all the cycles
#############################################
export fhbeg=00
export fhend=384
export fhinc=12

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

if [ "$DBNROOT" = "DBNROOT_OFF" ]; then
   export SENDDBN=NO
else
   export SENDDBN=${SENDDBN:-YES}
fi

#
# Set up model and cycle specific variables
#
export NET=gens
export RUN=gefs
export DBN_ALERT_TYPE=GEFS_METAFILE

export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export GEMPAKgefs=${GEMPAKgefs:-$HOMEgefs/gempak}

# export HOMEgempak=${NWROOT}/gempak
export FIXgempak=$GEMPAKgefs/fix
export USHgempak=$GEMPAKgefs/ush

#
# Now set up GEMPAK/NTRANS environment
#
. ${NWROOTp1}/gempak/.gempak

###################################
# Set up the UTILITIES
###################################
#export utilscript=${NWROOTp1}/util/ush
#export utilities=${NWROOTp1}/util/ush
#export utilexec=${NWROOTp1}/util/exec

# Run setup to initialize working directory and utility scripts
# setup.sh
# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMINs=${COMROOT}/nawips/prod
export COMINs_p1=${COMROOTp1}/nawips/prod
export COMIN=${COMROOT}/nawips/prod/${RUN}.${PDY}
# JY export COMINgfs=$(compath.py nawips/prod/gfs.${PDY})
export COMINgfs=$(compath.py gfs/prod/gfs.$PDY)/$cyc/gempak}
export COMINecmwf=$(compath.py nawips/prod/ecmwf.${PDY})
export COMINm1ecmwf=$(compath.py nawips/prod/ecmwf.${PDYm1})
export COMINm1=${COMROOT}/nawips/prod/${RUN}.${PDYm1}
export COMOUT=${COMROOT}/nawips/${envir}/${RUN}.${PDY}/meta

if [ ! -d $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
$HOMEgefs/scripts/exgefs_gempak_meta.sh.ecf
########################################################

msg="job has ended"
postmsg "$jlogfile" "$msg"

cat $pgmout

cd ${DATAROOT}
rm -rf $DATA

date

