#!/bin/ksh


#####################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
######################################################################

echo `date` $0 begin
set -xa
export PS4='$SECONDS + '

# 01/28/2013 New variables added for WCOSS and cross-machine unfication
export gefsmachine=${gefsmachine:-dell}
export gefsmpexec=${gefsmpexec:-mpirun}

###########################################
# Run gefs_config to get input parameters
###########################################
if [ "$RUN_ENVIR" = dev ]      ### For Developers
then
   # RLW 20141008 modify to obtain and use version for vertical structure
   . $basesource/nw$envir/*/versions/gefs_legacy.ver
   . $basesource/nwdev/gefs_legacy.${gefs_legacy_ver}/parm/gefs_config
fi

####################################
# obtain unique process id (pid) and make working directory
####################################
export pid=$$
if [ "$RUN_ENVIR" = dev ]    ### For Developers
then
   export TMPhome=${TMPhome:-$basetmp/tmpnwprd1}
else                       ### For Operations
   export TMPhome=$DATAROOT
fi
#export DATA=$TMPhome/${job}.${pid}
export DATA=${DATA:-$TMPhome/${job}.${pid}}

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=gens
export RUN=gfs

####################################
# File To Log Msgs
####################################
if [ "${envir}" = 'prod' ] || [ "${envir}" = 'para' ] || [ "${envir}" = 'test' ]
then
   export jlogfile=${jlogfile:-${DATA}/jlogfile}
else
   # DEV
   export jlogfile=${jlogfile:-$baselog/com/logs/jlogfile}
fi

export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################

if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
  export SENDCOM=${SENDCOM:-YES}
  export SENDDBN=${SENDDBN:-NO}
  export SENDECF=${SENDECF:-YES}
  export VERBOSE=${VERBOSE:-NO}
  export SENDDBN_GB2=${SENDDBN_GB2:-NO}
  export RERUN=${RERUN:-NO}

# JY - will remove the following? 02/07
  # Specify Execution Areas
#  export HOMEGLOBAL=${HOMEGLOBAL:-/nw${envir}}
#  export EXECGLOBAL=${EXECGLOBAL:-$HOMEGLOBAL/exec}
#  export USHGLOBAL=${USHGLOBAL:-$HOMEGLOBAL/ush}
#  export FIXGLOBAL=${FIXGLOBAL:-$HOMEGLOBAL/fix}
#  export PARMGLOBAL=${PARMGLOBAL:-$HOMEGLOBAL/parm}

  # RLW 20141008 modify to obtain and use version for vertical structure
  export HOMEgefs=${HOMEgefs_legacy:-/gpfs/dell1/nco/ops/nw${envir}/gefs_legacy.${gefs_legacy_ver}}
  export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
  export USHgefs=${USHgefs:-$HOMEgefs/ush}
  export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
  export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
else                             ### For Operations
  export SENDCOM=YES
  if [[ $cyc = 00 ]]; then
    export SENDDBN=NO
    export SENDDBN_GB2=NO
  else
    export SENDDBN=NO
    export SENDDBN_GB2=NO
  fi
  export SENDECF=YES
  export VERBOSE=NO
  export RERUN=NO

  # Specify Execution Areas
  export HOMEgefs=${HOMEgefs_legacy:-/gpfs/dell1/nco/ops/nw${envir}/gefs_legacy.${gefs_legacy_ver}}
  export HOMEGLOBAL=${HOMEGLOBAL:-$HOMEgefs}
  export HOMEglobal=${HOMEglobal:-$HOMEgefs}

  export EXECGLOBAL=${EXECGLOBAL:-$HOMEGLOBAL/exec}
  export USHGLOBAL=${USHGLOBAL:-$HOMEGLOBAL/ush}
  export FIXGLOBAL=${FIXGLOBAL:-$HOMEGLOBAL/fix}
  export PARMGLOBAL=${PARMGLOBAL:-$HOMEGLOBAL/parm}

  export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
  export USHgefs=${USHgefs:-$HOMEgefs/ush}
  export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
  export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
fi

####################################
# Specify Execution Areas
####################################
#export GRBINDEX=/nwprod/util/exec/grbindex

# JY - will remove - 02/07
#export HOMEUTIL=/nwprod/util
#export EXECUTIL=$HOMEUTIL/exec
#export FIXUTIL=$HOMEUTIL/fix

if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
#DHOU 03/22/201 for ZEUS/WCOSS
  case $gefsmachine in
    (zeus)
export GRBINDEX=$HOMEglobal/util/exec/grbindex
    ;;
  esac

  case $gefsmachine in
    (zeus)
export HOMEUTIL=$HOMEglobal/util
export EXECUTIL=$HOMEUTIL/exec
export FIXUTIL=$HOMEUTIL/fix
    ;;
    (wcoss)
export HOMEUTIL=$HOMEGLOBAL/util
export EXECUTIL=$HOMEUTIL/exec
export FIXUTIL=$HOMEUTIL/fix
    ;;
    (dell)
export HOMEUTIL=$HOMEGLOBAL/util
export EXECUTIL=$HOMEUTIL/exec
export FIXUTIL=$HOMEUTIL/fix
    ;;
  esac
fi

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Set up the UTILITIES
##############################
# JY - will remove? 02/10
#export utilscript=/nwprod/util/ush

#DHOU 03/22/2012 for ZEUS/WCOSS
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
   case $gefsmachine in
    (zeus)
  export utilscript=$HOMEglobal/util/ush
    ;;
    (wcoss)
  export utilscript=$HOMEGLOBAL/util/ush
    ;;
   esac
fi

##############################
# Run setup to initialize working directory and utility scripts
##############################
#sh $utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
#sh $utilscript/setpdy.sh
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
  export COMINgfs=${COMINgfs:-$(compath.py gfs/prod/gfs.${PDY})/$cyc/atmos}
  export COM_OUT=${COM_OUT:-/global/noscrub/$LOGBAME/com/${NET}/${envir}}
  export COMOUT=$COM_OUT/gefs_legacy.${PDY}
  export ENS_COM=$COMOUT
else                              ### For Operations
  export COMINgfs=${COMINgfs:-$(compath.py gfs/prod/gfs.${PDY})/$cyc/atmos}
  export COMOUT=$COMROOT/${NET}/${envir}/gefs_legacy.${PDY}
  export ENS_COM=$COMOUT
fi

mkdir -m 775 -p $COMOUT/$cyc/pgrba
mkdir -m 775 -p $COMOUT/$cyc/pgrb2a
mkdir -m 775 -p $COMOUT/$cyc/pgrbalr
mkdir -m 775 -p $COMOUT/$cyc/pgrb2alr
mkdir -m 775 -p $COMOUT/$cyc/misc

##############################################
echo set parameters using gefs.parm
##############################################

 . $PARMgefs/gefs.parm

export NTHREADS=1

export POSTGPVARS_HIGH="IDRTC=0,IOC=360,JOC=181,IDRT=0,IO=360,JO=181,MOO=120,MOW=30,MOOA=120,MOWA=30,"
export POSTGPVARS_LOW="IDRTC=0,IOC=144,JOC=73,IDRT=0,IO=144,JO=73,MOO=48,MOW=12,MOOA=48,MOWA=12,"

####################################
# Specify Restart File Names to Key Off
####################################
case $gfsgribedition in
  (1)
    restart_file_a=$COMINgfs/${RUN}.t${cyc}z.pgrbf
    restart_file_b=$COMINgfs/${RUN}.t${cyc}z.pgrbif
  ;;
  (2)
    restart_file_a=$COMINgfs/${RUN}.t${cyc}z.pgrb2.0p25.f
    restart_file_b=$COMINgfs/${RUN}.t${cyc}z.pgrb2.0p50.f
  ;;
esac


####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=900
export SLEEP_INT=5

####################################
# Specify Forecast Hour Range
####################################
export FHOUR_HIGH=$fhmax
export FHOUR_LOW=$fhmax
export FHINC_HIGH=6
export FHINC_LOW=6

export DO_HD_PGRB=NO
export HDMAX=00

####################################
# Specify Forecast Hour Range
####################################
export SHOUR=00
#export FHOUR_HIGH=$fhmax
export FHOUR_HIGH=$gfsfhmaxh
export fhoroglist=$gfsfhoroglist
export FHOUR_LOW=$fhmax
export FHINC_HIGH=6
#export FHINC_LOW=6
export FHINC_LOW=12

export DO_HD_PGRB=NO
export HDMAX=00

#
# DLM - Added to Try and Debug Comm Subsystem Errors
# Problems in ENP5P On 20030730/12 UTC
# Problems in ENP4P On 20030731/12 UTC
#
export MP_INFOLEVEL=6

env | sort

#################################
# Run High Res Prdgen if Needed
#################################
if test $SHOUR -le $FHOUR_HIGH
then
   export FHINC=$FHINC_HIGH
   export FHOUR=$FHOUR_HIGH
   export DO_LOW_RES=YES 
   if (( $gfsgribedition == 1 )); then 
      $HOMEgefs/scripts/exgefs_prdgen_gfs.sh.ecf
   elif (( $gfsgribedition == 2 )); then 
      $HOMEgefs/scripts/exgefs_prdgen_gfs_grb2.sh.ecf
   fi  
   export SHOUR=`expr $FHOUR_HIGH + $FHINC_LOW`
fi
#################################
# Run Low Res Prdgen if Needed
#################################
if test $SHOUR -lt $FHOUR_LOW
then
   export FHINC=$FHINC_LOW
   export FHOUR=$FHOUR_LOW
   export DO_LOW_RES=YES 
   export POSTGPVARS_HIGH=$POSTGPVARS_LOW
   if (( gfsgribedition == 1 )); then 
      $HOMEgefs/scripts/exgefs_prdgen_gfs.sh.ecf
   elif (( gfsgribedition == 2 )); then 
      $HOMEgefs/scripts/exgefs_prdgen_gfs_grb2.sh.ecf
   fi  
fi

msg="$job completed normally"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $TMPhome
rm -rf $DATA

echo `date` $0 end
