#!/bin/ksh 
#####################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
# September 2014, Dingchen Hou   Scripts are modified to process grib2 pgrb files
# February 2015, Dingchin Hou   Scripts changed to vertical structure and cleaned following NCO requirements
######################################################################

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

export gefsmachine=${gefsmachine:-wcoss}
export gefsmpexec=${gefsmpexec:-mpirun.lsf}

export GRIBVERSION=${GRIBVERSION:-grib2}

###########################################
# Run gefs_config to get input parameters
###########################################
if [ "$RUN_ENVIR" = dev ]      ### For Developers
then
# . $basesource/nw${envir}/versions/gefs.ver
  . $basesource/nwdev/parm/gefs_config
fi

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

export SUBJOB=$SUBJOB

######################################
# Set up the cycle variable
######################################
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=stat

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
  export SENDCOM=${SENDCOM:-YES}
  export SENDDBN=${SENDDBN:-NO}
  export SENDECF=${SENDECF:-YES}
  export RERUN=${RERUN:-NO}

  # Specify Execution Areas
  export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}

  export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
  export USHgefs=${USHgefs:-$HOMEgefs/ush}
  export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
  export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export REDOUT='1>>'
export REDERR='2>'

##############################################
echo set parameters using gefs.parm
##############################################
. $PARMgefs/gefs.parm
. $PARMgefs/gefs_ensstat.parm

##############################
# Run setup to initialize working directory and utility scripts
##############################
#sh setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=$COMROOT/${NET}/${envir}/gefs.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/gefs.${PDY}
export COMINm1=$COMROOT/${NET}/${envir}/gefs.${PDYm1}

mkdir -m 775 -p $COMOUT/$cyc/pgrb2a
mkdir -m 775 -p $COMOUT/$cyc/pgrb2alr
mkdir -m 775 -p $COMOUT/$cyc/pgrb2ap5

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=900
export SLEEP_INT=5

export NTHREADS=1
####################################
# Specify Forecast Hour Range
####################################
# allow different forecast lengths in different cycles
if [[ $envir = dev ]]; then
  case $cyc in
    (00)  fhmax=$fhmax00 ;;
    (06)  fhmax=$fhmax06 ;;
    (12)  fhmax=$fhmax12 ;;
    (18)  fhmax=$fhmax18 ;;
    (*)
      echo cyc=$cyc IS UNDEFINED 
      export pgm=JGEFS_ENSSTAT
      export err=111
    ;;
  esac
fi
if (( fhmaxh > fhmax )); then
  fhmaxh=$fhmax
fi

export FHINC=06

fcstlong=true
case $FORECAST_SEGMENT in
  (hr)
    # high resolution segment
    export FHINC=03
    export SHOUR=00
    if [[ $fcstlong = true ]]; then
      export FHOUR=$fhmaxh
    else
      export FHOUR=06
    fi
  ;;
  (lr)
    # low resolution segment
    export SHOUR=$(( $fhmaxh + FHINC ))
    if [[ $fcstlong = true ]]; then
      export FHOUR=$fhmax
    else
      export FHOUR=06
    fi
  ;;
  (*)
    # whole forecast period
    export SHOUR=00
    if [[ $fcstlong = true ]]; then
      export FHOUR=$fhmax
    else
      export FHOUR=06
    fi
  ;;
esac
case $SUBJOB in
  (A)
    export gridlist="hr lr";
    export FHINC=06;;     
  (B)
    export gridlist="p5";
    export makepgrba="no";;
  (*)
    export gridlist="hr lr p5";;
esac    

echo FORECAST_SEGMENT=$FORECAST_SEGMENT
echo FHINC=$FHINC      
echo SHOUR=$SHOUR
echo FHOUR=$FHOUR

env | sort

# Execute the script

export ext_h=""
if [[ $GRIBVERSION == grib2 ]]; then
 $HOMEgefs/scripts/exgefs_ensstat.sh.ecf
else
 $HOMEgefs/scripts/exgefs_ensstat_grb1.sh.ecf
fi

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  cd $DATAROOT
  rm -rf $DATA
fi
