#!/bin/ksh 

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

export APRUN=${gefsmpexec:-mpirun}
export APRUN_CHGRES=${APRUN_CHGRES:-"aprun -j 1 -n 1 -N 1 -d 12 -cc depth"}
export APRUN_RECENT=${APRUN_RECENT:-"aprun -j 1 -n $total_tasks -N $taskspernode -d $OMP_NUM_THREADS -cc depth"}



############################
# Set up cycle varaible
############################

export cycle=t${cyc}z
export cycle_fcst=t${cyc_fcst}z

if (( cyc == cyc_fcst )); then
	export cycsuffix=false
	export fcstlong=true
else
	export fcstlong=false
	export cycsuffix=true
fi

####################################
# obtain unique process id (pid) and identify working directory
####################################
export pid=$$
export DATA=$DATAROOT/gefs_init_$PDY$cyc.$envir.save
cd $DATA

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

 
####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export HOMEgsm=${HOMEgsm:-$NWROOT/gsm.${gsm_ver}}
#export HOMEenkf=${HOMEenkf:-$NWROOTp1/enkf.${enkf_ver}}

export EXECgsm=${EXECgsm:-$HOMEgsm/exec}
export USHgsm=${USHgsm:-$HOMEgsm/ush}
export FIXgsm=${FIXgsm:-$HOMEgsm/fix/fix_am}
export PARMgsm=${PARMgsm:-$HOMEgsm/parm}

export EXECGLOBAL=${EXECgsm:-$HOMEgsm/exec}
export USHGLOBAL=${USHgsm:-$HOMEgsm/ush}
export FIXGLOBAL=${FIXgsm:-$HOMEgsm/fix/fix_am}

export EXECgefs=${EXECgefs:-$HOMEGgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

##############################################
echo set parameters using gefs.parm
##############################################

. $PARMgefs/gefs.parm
. $PARMgefs/gefs_init.parm

env | sort

if [[ $gfssource != prod ]]; then
        export COMINgfs=${COMINgfs_base}${PDY}/$cyc
        export COMINenkf=${COMINenkf_base}
fi

##############################################
# for global_chgres.sh
##############################################
export SLMASK=/dev/null

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

#####
export XC=.x
export GETATMENSMEANEXEC=${GETATMENSMEANEXEC:-${HOMEgfs}/exec/getsigensmeanp_smooth$XC}
RECENATMEXEC=${RECENATMEXEC:-$HOMEgfs/exec/recentersigp.x}
export CHGRESEXEC=$HOMEgsm/exec/chgres_recenter.exe

echo location of nemsioget
#export nemsioget=$nemsioget
export nemsioget=$EXECgsm/nemsio_get

##############################################
echo list environment before running script
##############################################

env | sort

#############################################################
# Execute the script
#############################################################
$HOMEgefs/scripts/exgefs_init_process.sh.ecf

cat $pgmout

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Save the working directory
# for the COMBINE job
##############################
