#!/bin/ksh 
#####################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
# November 2014, Dingchen Hou   Scripts are modified to process grib2 pgrb files
# February 2015, Dingchin Hou   Scripts changed to vertical structure and cleaned following NCO requirements
######################################################################

#$SMSBIN/smsinit $LOADL_STEP_ID 
echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '

# 01/28/2013 New variables added for WCOSS and cross-machine unfication
export gefsmachine=${gefsmachine:-wcoss}
export gefsmpexec=${gefsmpexec:-mpirun.lsf}
export machine=${gefsmachine:-wcoss}
export GRIBVERSION=${GRIBVERSION:-grib2}
export gefsgribedition=${gefsgribedition:-2}

###########################################
# Run gefs_config to get input parameters
###########################################
if [ "$RUN_ENVIR" = dev ]      ### For Developers
then
  . $basesource/nwdev/parm/gefs_config
# . $basesource/nwdev/parm/gefs_config_old
else
  VERSION_FILE=/nw{$envir}/versions/gefs.ver
  if [-f $VERSION_FILE]; then
     . $VERSION_FILE
  else
     ecflow_client --abort
     exit
  fi
fi

export HOMEgefs=${HOMEgefs}
export HOMEutil=${HOMEROOT:-/nwprod/util}
export HOMEgrib=${GRIBROOT:-/nwprod/util}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA=$DATAROOT/${job}.${pid}
#export DATA=$DATA_IN/cqpd.${pid}

mkdir -p $DATA
cd $DATA

######################################
# Set up the cycle variable
######################################
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=stat

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
  export SENDCOM=${SENDCOM:-YES}
  export SENDDBN=${SENDDBN:-NO}
  export SENDSMS=${SENDSMS:-YES}
  export SENDECF=${SENDECF:-YES}
  export SENDDBN_GB2=${SENDDBN_GB2:-NO}
  export RERUN=${RERUN:-NO}

  # Specify Execution Areas
  export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
  export USHgefs=${USHgefs:-$HOMEgefs/ush}
  export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
  export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Set up the UTILITIES
##############################
export EXECutil=$HOMEutil/exec
export FIXutil=$HOMEutil/fix
export USHutil=$HOMEutil/ush
export utilscript=${USHutil}

export CNVGRIB=${CNVGRIB:-/$EXECutil/cnvgrib21_gfs}

##############################
# Run setup to initialize working directory and utility scripts
##############################
sh $USHutil/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
sh $USHutil/setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMINGEST=$TMPCOM/ingest/prod
export COMINGEST=${COMINGEST:-/ensemble/noscrub/Yan.Luo/com-ingest-prod}
export COMIN=${COM_IN:-${COMROOT}/com/${NET}/${envir}}
export COMOUT=$COMROOT/com/${NET}/${envir}/gefs.${PDY}/${cyc}/ensstat

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
# Execute the script
if (( cyc == 00 )); then
 $HOMEgefs/scripts/exglobal_enscqpf.sh.ecf
else
 echo skip cqpf processing in development for cyc=$cyc
fi
#############################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
#cd $DATA_IN
#rm -rf $DATA

#$SMSBIN/endt
