#!/bin/ksh 
# This is a new job to process the EnKF 6hr fcst by calculate the tracks
echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

export APRUN=${gefsmpexec_mpmd:-"mpirun -n $total_tasks cfp mpmd_cmdfile"}

############################
# Set up cycle varaible
############################

export cycle=t${cyc}z
export cycle_fcst=t${cyc_fcst}z

if (( cyc == cyc_fcst )); then
	export cycsuffix=false
	export fcstlong=true
else
	export fcstlong=false
	export cycsuffix=true
fi

####################################
# obtain unique process id (pid) and make working directory
####################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.$gefs_ver}
#export HOMEgsm=${HOMEgsm:-${NWROOT}/gsm.${gsm_ver}}

#export EXECgsm=${EXECgsm:-$HOMEgsm/exec}
#export USHgsm=${USHgsm:-$HOMEgsm/ush}
#export FIXgsm=${FIXgsm:-$HOMEgsm/fix/fix_am}
#export PARMgsm=${PARMgsm:-$HOMEgsm/parm}


export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export UTILgefs=${UTILgefs:-$HOMEgefs/util}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

##############################################
echo set parameters using gefs.parm
##############################################
. $PARMgefs/gefs.parm
. $PARMgefs/gefs_init.parm

env | sort

# for global_chgres.sh
##############################################
export SLMASK=/dev/null

##############################################
# Define the time for the EnKF previous cycle
##############################################
export pdycycp=`$NDATE -$fhrp $PDY$cyc`
export pdyp=`echo $pdycycp|cut -c1-8`
export cycp=`echo $pdycycp|cut -c9-10`

##############################################
# Define the time 6h ago and after for tracking
##############################################
d6ahead_ymdh=` $NDATE 6 ${PDY}${cyc}`
d6ago_ymdh=` $NDATE -6 ${PDY}${cyc}`
export d6ahead_ymd=`echo $d6ahead_ymdh|cut -c1-8`
export d6ago_ymd=`echo $d6ago_ymdh|cut -c1-8`
export d6ahead_cyc=`echo $d6ahead_ymdh|cut -c9-10`
export d6ago_cyc=`echo $d6ago_ymdh|cut -c9-10`

##############################################
# Define COM directories
##############################################
if [[ $gfssource != prod ]]; then
        export COMINgfs=${COMINgfs_base}${PDY}/$cyc
        export COMINgfs6ago=${COMINgfs_base}${d6ago_ymd}/${d6ago_cyc}
        export COMINgfs6ahead=${COMINgfs_base}${d6ahead_ymd}/${d6ahead_cyc}
        export COMINenkf=${COMINenkf_base}$pdyp
fi

export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)/gfs.${PDY}/$cyc}
export COMINenkf=${COMINenkf:-$(compath.py gfs/prod)/enkfgdas.$pdyp} 
export COMINatcfsyn=${COMINatcfsyn:-$(compath.py arch/prod/syndat)}
export COMINgfs6ago=${COMINgfs6ago:-$(compath.py gfs/prod)/gfs.${d6ago_ymd}/${d6ago_cyc}}
export COMINgfs6ahead=${COMINgfs6ahead:-$(compath.py gfs/prod)/gfs.${d6ahead_ymd}/${d6ahead_cyc}}

export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

export COMOUTprevcyc=$COMROOT/${NET}/${envir}/${RUN}.${pdyp}/$cycp 
mkdir -m 775 -p $COMOUTprevcyc

#######
#echo location of sighdr executable

#export sighdrexec=$EXECgsm/global_sighdr

#echo sighdrexec=$sighdrexec


#echo location of chgres script and executable
# Change Resolution script and executable
#xport chgresush=$USHgsm/global_chgres.sh
#xport CHGRESEXEC=$EXECgsm/global_chgres

#cho chgresush=$chgresush
#cho CHGRESEXEC=$CHGRESEXEC
#########################
echo location of tracking executable
export exectrkdir=$HOMEgefs/util/exec

echo location of nemsioget
#export nemsioget=$nemsioget
#xport nemsioget=$EXECgsm/nemsio_get

##############################################
echo list environment before running script
##############################################

echo
env | sort
echo
$HOMEgefs/scripts/exgefs_enkf_track.sh.ecf

#############################################################

cat $pgmout

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

echo `date` $0 `date -u` end
