#!/bin/sh

########################################
# Creates GEFS AVGSPR META files for NAWIPS
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

####################################
# obtain unique process id (pid) and make working directory
####################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir -p $DATA
cd $DATA

######################################
# Set up the cycle variable
######################################
export cycle=${cycle:-t${cyc}z}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}
export model=${model:-ensemble}

####################################
# File To Log Msgs
####################################
#export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# SENDECF  - Flag Events on ECF
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export VERBOSE=${VERBOSE:-NO}
if [ "$DBNROOT" = "DBNROOT_OFF" ]; then
   export SENDDBN=NO
else
   export SENDDBN=${SENDDBN:-YES}
fi

################################
# Set up the HOME directory
################################
export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

######################################
# Set up the GEMPAK directory
#######################################
export GEMPAKgefs=${GEMPAKgefs:-$HOMEgefs/gempak}
export FIXgempak=${FIXgempak:-$GEMPAKgefs/fix}
export USHgempak=${USHgempak:-$GEMPAKgefs/ush}

############################################
# Run gefs.parm to get input variables
############################################
. $PARMgefs/gefs.parm

############################################
# Set up model and cycle specific variables
############################################
export fhbeg=${fhbeg:-0}
export fhend=${fhmax:-384}
export fhinc=${fhinc:-12}

export FHMAXHF=${FHMAXHF:-240}
export FHOUTHF=${FHOUTHF:-3}
export FHOUTLF=${FHOUTLF:-6}

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-GEFS_METAFILE}

cp $FIXgempak/datatype.tbl datatype.tbl

##############################################
# Define COM directories
##############################################
export COMIN=${COMROOT}/nawips/${envir}/${RUN}.${PDY}
export COMOUT=${COMROOT}/nawips/${envir}/${RUN}.${PDY}/meta

if [ ! -d $COMOUT ] ; then
    mkdir -p -m 775 $COMOUT
fi
 
env

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
$HOMEgefs/scripts/exgefs_avgspr_gempak_meta.sh.ecf
ERR=$?
echo $ERR
########################################################

msg="job has ended"
postmsg "$jlogfile" "$msg"

cat $pgmout

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

echo `date` $0 `date -u` end

exit $ERR
