#!/bin/ksh

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

export machine=$machine
export gefsmpexec=${gefsmpexec:-mpirun}
export APRUN=${gefsmpexec:-mpirun}

export RUNMEM=$RUNMEM
export mem=`echo $RUNMEM|cut -c3-5`

export ENS_NUM=1
echo "ENS_NUM=$ENS_NUM"

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
mkdir $DATA/INPUT
cd $DATA

############################
# Set up cycle varaible
############################
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}
export COMPONENTwave=${COMPONENTwave:-${RUN}wave}
#export NTHREADS=1

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# Define RERUN Parameter: default to RESTART if not previously set
#
# Set RERUN=RESTART to find the last set of complete SFCSIG files and restart the forecast at that point
# (corresponds to previous setting RERUN=NO)
# Set RERUN=YES to remove all forecast products and log files, if any, and start over from the conditions
#
# In case of FORECAST failure, set RERUN=RESTART if necessary in FORECAST, NCEPPOST, and PRDGEN jobs
# In case of NCEPPOST failure, set RERUN=RESTART if necessary in NCEPPOST, and PRDGEN jobs
# In case of PRDGEN   failure, set RERUN=RESTART if necessary in PRDGEN jobs
####################################
echo "input setting RERUN=$RERUN"

export RERUN=${RERUN:-NO}
#
echo "current setting RERUN=$RERUN"

# Specify Execution Areas
export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export HOMEgfs=${HOMEgfs:-$HOMEgefs}
export EXECgfs=$HOMEgfs/exec
export USHgfs=$HOMEgfs/ush
export FIXgfs=$HOMEgfs/fix
export PARMgfs=$HOMEgfs/parm

# Path to HOME Directory
export HOMEwave=${HOMEwave:-${HOMEgfs}}
export PARMwave=${PARMwave:-$HOMEgefs/parm}
export CODEwave=${CODEwave:-${HOMEgfs}/WW3/model}
export EXECwave=${EXECwave:-$HOMEwave/exec}
export FIXwave=${FIXwave:-$FIXgefs/fix_wave}
export PARMwave=${PARMwave:-$HOMEwave/parm/wave}
export USHwave=${USHwave:-$HOMEwave/ush}
export EXECcode=${EXECcode:-$CODEwave/exe}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

# Set COM Paths and GETGES environment
export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${COMPONENTwave}.${PDY}/${cyc}}
export COMOUT=${COMOUT:-${COMOUTwave}/${COMPONENTwave}.${PDY}/${cyc}}

#Names used in exglobal_fv3.sh
export BASE_GSM=${BASE_GSM:-$HOMEgfs}
export FIX_DIR=$FIXgfs
export FIX_AM=$FIX_DIR/fix_am
export FIXfv3=$FIX_DIR/fix_fv3_gmted2010
export FIXchem=$FIX_DIR/fix_chem/fimdata_chem/fimdata_chem_G6_Li

##############################################
# Define COM and GES directories
##############################################
if [[ $FORECAST_SEGMENT = hr ]] ; then
	echo "Integrate the model for the Half-Month range segment"
	FHINI=0
elif [[ $FORECAST_SEGMENT = lr ]] ; then
	echo "Integrate the model for the Longer Range segment"
	FHINI=$fhmaxh
	export cplwav=.false.
else
	msg="FATAL ERROR:  Incorrect value of FORECAST_SEGMENT=$FORECAST_SEGMENT"
	echo "`date`   $msg"
	echo "The Forecast job will be aborted!!!!"
	postmsg "$jlogfile" "$msg"
	export pgm=JENS_FCST
	export err=911
	err_chk
fi # [[ $FORECAST_SEGMENT = hr ]]

echo FORECAST_SEGMENT = $FORECAST_SEGMENT
echo FHINI=$FHINI
echo ENS_SPS = $ENS_SPS
echo RUN_CONCURRENT = $RUN_CONCURRENT

export GESIN=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
export GESOUT=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
export COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}
export SSTDIR=${SSTDIR:-$COMIN/${cyc}/cfssst}

export memdir=$GESIN/$mem
export gmemdir=$GESIN/$mem
export ICSDIR=$GESIN/$mem
export FCSTDIR=$COMOUT/$cyc/sfcsig
export RSTDIR=$GESIN/$mem/RESTART
export RSTDIR_TMP=$RSTDIR

mkdir -m 775 -p $COMOUT/$cyc/sfcsig
mkdir -m 775 -p $COMOUT/$cyc/misc/fcst
mkdir -m 775 -p $COMOUT/$cyc/restart/$mem

mkdir -m 755 -p $GESIN/$mem/RESTART

#ln -s $GESOUT/$mem/RESTART $DATA/RESTART

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg

##############################################
echo set parameters using gefs.parm
##############################################
. $PARMgefs/gefs.parm
. $PARMwave/gefs_wave.parm


if [[ $FORECAST_SEGMENT = hr ]] ; then
	export RERUN="NO"
	FHINI=${FHINI:-0}
fi

if [[ $FORECAST_SEGMENT = lr ]] ; then
	export RERUN="YES"
	FHINI=${FHINI:-$fhmaxh}
	export CDATE_RST=$($NDATE +$fhmaxh $PDY$cyc)
fi

if [[ $FORECAST_SEGMENT = hr ]] ; then
	CASE=$CASEHR; FHMAX=$fhmaxh; FHOUT=$FHOUTLF; FHZER=6;
	MTNRSL=$MTNRSLFV; LONB=$LONBFV; LATB=$LATBFV;
	FHMAX_HF=$FHMAXHF; FHOUT_HF=$FHOUTHF; 
	FHINI=$FHINI;
	(( LEVS = LEVSHR + 1 ))
elif [[ $FORECAST_SEGMENT = lr ]] ; then
	CASE=$CASELR; FHMAX=$fhmax; FHOUT=$FHOUTLF; FHZER=6;
 	MTNRSL=$MTNRSLLR; LONB=$LONBLR; LATB=$LATBLR;
	FHMAX_HF=$FHMAXHF; FHOUT_HF=$FHOUTHF;
	FHINI=$FHINI;
	(( LEVS = LEVSLR + 1 ))
else
	FORECAST_SEGMENT=$FORECAST_SEGMENT is not supported !
	exit 9
fi

export FHMIN=$FHINI

#  The VEGTYPE fix file:
export FNVETC=${FNVETC:-${FIX_AM}/global_vegtype.igbp.t$MTNRSL.rg.grb}
export FNTSFC=${FNTSFC:-${FIX_AM}/RTGSST.1982.2012.monthly.clim.grb}
export FNAISC=${FNAISC:-${FIX_AM}/CFSR.SEAICE.1982.2012.monthly.clim.grb}
export FNABSC=${FNABSC:-${FIX_AM}/global_mxsnoalb.uariz.t$MTNRSL.rg.grb}
export FNALBC=$FIX_AM/global_snowfree_albedo.bosu.t$MTNRSL.rg.grb
export FNALBC2=$FIX_AM/global_albedo4.1x1.grb
export FNSMCC=$FIX_AM/global_soilmgldas.t$MTNRSL.grb
export FNSOTC=$FIX_AM/global_soiltype.statsgo.t$MTNRSL.rg.grb

####################################
# Create member list
####################################

#
# Forecast Input Variables
#
. $PARMgefs/gefs_fcst.parm
export restart_interval=${fhrestart:-1000}
export fhstoch=$restart_interval

if [[ $FORECAST_SEGMENT = hr ]] ; then
#	(( FHMAX = FHMAX + FHOUTLF ))
	(( FHMAX = FHMAX + 1 ))
fi

export other_restart_time=${other_restart_time:-6}
export fhstoch=${fhstoch:-"-999.0"}  # forecast hour to dump random patterns
export stochini=${stochini:-".false."}  # true= read in pattern, false=initialize from seed

if [[ $RERUN = "YES" ]] ; then
	export warm_start=.true.
	export restart_hour=$FHMIN
	export restart_run=.true.    
	export output_1st_tstep=.true.
	export stochini=.true.
fi

#
# Forecast Input Variables
#
#--------------------------------------------
export KMP_AFFINITY=disabled
export OMP_STACKSIZE=1024m
export MP_LABELIO=yes

# ----------------------------------
# user account 
# ----------------------------------

if [[ $mem = c00 ]] ;then 
	MEMBER=$((npert+1))
	WAV_MEMBER="00"
else
	MEMBER=`echo $mem|cut -c2-3`
	WAV_MEMBER=$MEMBER
fi
export MEMBER=$MEMBER
memchar=mem$(printf %03i $MEMBER)

export SET_STP_SEED=${SET_STP_SEED:-"YES"}

if [[ $FORECAST_SEGMENT = hr ]] ; then

	if [[ $DO_SPPT = YES ]] ; then
		export SPPT=$SPPT_hr
		export ISEED_SPPT=$ISEED_SPPT_hr
		export SPPT_LOGIT=$SPPT_LOGIT_hr
		export SPPT_TAU=$SPPT_TAU_hr
		export SPPT_LSCALE=$SPPT_LSCALE_hr
		export sppt_sfclimit=$sppt_sfclimit_hr
	#	export sppt_sigtop1=$sppt_sigtop1_hr
	#	export sppt_sigtop2=$sppt_sigtop2_hr
	fi

	if [[ $DO_SHUM = YES ]] ; then
		export SHUM=$SHUM_hr
		export ISEED_SHUM=$ISEED_SHUM_hr
		export SHUM_TAU=$SHUM_TAU_hr
		export SHUM_LSCALE=$SHUM_LSCALE_hr
	#	export shum_sigefold=$shum_sigefold_hr
	fi

	if [[ $DO_SKEB = YES ]] ; then
		export SKEB=$SKEB_hr
		export ISEED_SKEB=$ISEED_SKEB_hr
		export SKEB_TAU=$SKEB_TAU_hr
		export SKEB_LSCALE=$SKEB_LSCALE_hr
		export SKEBNORM=${SKEBNORM:-"1"}
	fi

fi

if [[ $FORECAST_SEGMENT = lr ]] ; then

	if [[ $DO_SPPT = YES ]] ; then
		export SPPT=$SPPT_hr
		export ISEED_SPPT=$ISEED_SPPT_hr
		export SPPT_LOGIT=$SPPT_LOGIT_hr
		export SPPT_TAU=$SPPT_TAU_hr
		export SPPT_LSCALE=$SPPT_LSCALE_hr
		export sppt_sfclimit=$sppt_sfclimit_hr
	#	export sppt_sigtop1=$sppt_sigtop1_hr
	#	export sppt_sigtop2=$sppt_sigtop2_hr
	fi

	if [[ $DO_SHUM = YES ]] ; then
		export SHUM=$SHUM_hr
		export ISEED_SHUM=$ISEED_SHUM_hr
		export SHUM_TAU=$SHUM_TAU_hr
		export SHUM_LSCALE=$SHUM_LSCALE_hr
	#	export shum_sigefold=$shum_sigefold_hr
	fi

	if [[ $DO_SKEB = YES ]] ; then
		export SKEB=$SKEB_hr
		export ISEED_SKEB=$ISEED_SKEB_hr
		export SKEB_TAU=$SKEB_TAU_hr
		export SKEB_LSCALE=$SKEB_LSCALE_hr
		export SKEBNORM=${SKEBNORM:-"1"}
	fi

fi

#
# Forecast Input Variables
#
export fcstscript=${fcstscript:-$HOMEgfs/scripts/exglobal_fcst_nemsfv3gfs.sh}
export FORECASTSH=$fcstscript
export FCSTEXECDIR=${FCSTEXECDIR:-$EXECgefs}
export PARM_FV3DIAG=${PARM_FV3DIAG:-$PARMgfs/parm_fv3diag}
export ROTDIR=${ROTDIR:-$DATA}

export APRUN=${APRUN:-""}

echo $fcstscript
echo $FORECASTSH
echo $FCSTEXECDIR
echo $FCSTEXEC
echo $PARM_FV3DIAG
echo $APRUN

NCP="/bin/cp -p"

#USE_RESTART=NO                      #use restart file under COMROT/RESTART if run is interruptted
#FHSTRT=6                            #restart from a given hour if USE_RESTART=YES
SEND=NO    
export VERBOSE=YES

#echo "-----end of CONFIG in $0 --------"

################################################################################
export CDATE=$PDY$cyc
export rCDUMP=$RUNMEM
export CDUMP=$RUNMEM

LINK=NO   # link is done in the $FORECAST script
if [ $LINK = "YES" ]; then
    if [ $OUTPUT_GRID = "gaussian_grid" ]; then
	    # Link output files
	    hr=$FHINI
	    while (( hr < FHMAX_HF )); do
		    fhr=$(printf "%03.0f" $hr)
		    ln -s $FCSTDIR/${RUNMEM}.${cycle}.atmf$fhr.nemsio $DATA/$CDUMP.${cycle}.atmf$fhr.nemsio
		    ln -s $FCSTDIR/${RUNMEM}.${cycle}.sfcf$fhr.nemsio $DATA/$CDUMP.${cycle}.sfcf$fhr.nemsio
		    ln -s $FCSTDIR/${RUNMEM}.${cycle}.logf$fhr.nemsio $DATA/$CDUMP.${cycle}.logf$fhr.nemsio
		    export hr=$(expr $hr + $FHOUT_HF)
	    done
	    while (( hr <= FHMAX )); do
		    fhr=$(printf "%03.0f" $hr)
		    ln -s $FCSTDIR/${RUNMEM}.${cycle}.atmf$fhr.nemsio $DATA/$CDUMP.${cycle}.atmf$fhr.nemsio
		    ln -s $FCSTDIR/${RUNMEM}.${cycle}.sfcf$fhr.nemsio $DATA/$CDUMP.${cycle}.sfcf$fhr.nemsio
		    ln -s $FCSTDIR/${RUNMEM}.${cycle}.logf$fhr.nemsio $DATA/$CDUMP.${cycle}.logf$fhr.nemsio
		    export hr=$(expr $hr + $FHOUT)
	    done
    else
	    for n in `seq 1 $ntiles`; do
		    for file in atmos_4xdaily. atmos_static. fv3_history. fv3_history2d. grid_spec. nggps2d. nggps3d.; do
			    # ln -s $ROTDIR/$file\tile$n.nc $DATA/$file\tile$n.nc

			    # touch $SFCSIG/$mem/$file\tile$n.nc
			    # ln -s $SFCSIG/$mem/$file\tile$n.nc $memdir/$file\tile$n.nc
			    ;
		    done
	    done
    fi # [ $OUTPUT_GRID = "gaussian_grid" ]
fi # $LINK

if [[ $cplwav = ".true." ]]; then
	# Settings for Wavewatch III
	export COMINWW3=${COMINWW3:-${COMROOT:?}/${NET}/${envir}}
	export COMOUTWW3=$COMROOT/${NET}/${envir}
fi # [[ $cplwav = ".true." ]]

if [[ $cplchm = ".true." && $warm_start = ".true." ]]; then
    # Link restart files for next cycle
	next_date=$($NDATE +$gefs_cych $CDATE)
	# next_date=$($NDATE +$restart_interval $CDATE)
    next_PDY=$(echo $next_date | cut -c1-8)
    next_cyc=$(echo $next_date | cut -c9-10)
	last_rstdir=$COMOUT/$cyc/restart/$mem
    if [[ ! -d $DATA/RESTART ]]; then mkdir -p $DATA/RESTART; fi
	ln -sf $last_rstdir/${next_PDY}.${next_cyc}0000.coupler.res $DATA/RESTART/${next_PDY}.${next_cyc}0000.coupler.res
	ln -sf $last_rstdir/${next_PDY}.${next_cyc}0000.fv_core.res.nc $DATA/RESTART/${next_PDY}.${next_cyc}0000.fv_core.res.nc
	for kind in fv_tracer.res fv_core.res fv_srf_wnd.res phy_data sfc_data; do
		for tile in tile1 tile2 tile3 tile4 tile5 tile6; do
			ln -sf $last_rstdir/${next_PDY}.${next_cyc}0000.${kind}.${tile}.nc $DATA/RESTART/${next_PDY}.${next_cyc}0000.${kind}.${tile}.nc
		done
	done

fi # [[ $cplchm = ".true." && $warm_start = ".true." ]]

export increment_file=$ICSDIR/fv3_increment.nc

export FIX_DIR=$FIXgfs
export FIX_AM=$FIX_AM

if [[ $read_increment = ".true." && $warm_start = ".true." ]]; then
	# Make sure increment file exists before using warm start
	if [[ ! -f $increment_file ]]; then
		echo "WARNING: Warm-start requested but no increment file present, reverting to cold-start!"
		export warm_start=".false."
		export read_increment=".false."
	fi
fi

if [[ $RERUN = "YES" ]]; then
	fhr=$(printf "%03.0f" $fhmaxh)
	cp -pr $GESIN/$mem/RESTART/stoch_out.F000$fhr $DATA/stoch_ini 
fi

$FORECASTSH
ERR=$?

cp -pr $DATA/stoch_out.F* $GESIN/$mem/RESTART  

if [ $ERR = 0 ]; then
    msg="$job completed normally!"
else
    msg="FATAL ERROR: $job failed!"
fi
postmsg "$jlogfile" "$msg"

if [[ $KEEPDATA != "YES" ]]; then
    cd $DATAROOT
    rm -rf $DATA
fi

echo `date` $0 `date -u` end

exit $ERR
