#!/bin/ksh 
################# lines between these markers have been modified for dev begin
################# lines between these markers have been modified for dev end
###testb
# lines between ###testb and ###teste not needed for production
###teste

$SMSBIN/smsinit $LOADL_STEP_ID 
echo `date` $0 `date -u` begin

set -xa
####################################

# 01/28/2013 New variables added for WCOSS and cross-machine unfication
export gefsmachine=${gefsmachine:-wcoss}
export gefsmpexec=${gefsmpexec:-mpirun.lsf}

if [[ $gefsmachine = zeus ]]; then
   export  gefspoe="$gefsmpexec $basesource/nw$envir/exec/zeus-poe"
 else
     export gefspoe=$gefsmpexec
 fi
###############
#if [ "$RUN_ENVIR" = dev ]   ### For Developers
#then
#  . $basesource/nwdev/parm/gefs_config
#fi
###########################################
# Run gefs_config to get input parameters
###########################################
if [ "$RUN_ENVIR" = dev ]   ### For Developers
then
################# lines between these markers have been modified for dev begin
  . $basesource/nwdev/parm/gefs_config
else
  VERSION_FILE=/nw{$envir}/versions/gefs.ver
  if [-f $VERSION_FILE]; then
    . $VERSION_FILE
  else
    ecflow_client --abort
    exit
  fi
fi

export HOMEgefs=${HOMEgefs}
export HOMEgsm=${HOMEgsm}
export HOMEutil=${HOMEutil:-/nwprod/util}

# #### 05/05/99 ###############################
# SETUP ENS INITIALIZATION PROCESSING VARIABLES
# #############################################

####################################
# obtain unique process id (pid) and identify working directory
####################################
export pid=$$
if [ "$RUN_ENVIR" = dev ]    ### For Developers
then
  export DATA_IN=${DATA_IN:-$basetmp/tmpnwprd}
else
  export DATA_IN=/tmpnwprd
fi

  export DATA=$DATA_IN/gefs_init_$PDY$cyc.$envir.save

echo DATA=$DATA
cd $DATA


export cycle=t${cyc}z
export cycle_fcst=t${cyc_fcst}z

echo cyc=$cyc cyc_fcst=$cyc_fcst
echo cycle=$cycle cycle_fcst=$cycle_fcst

if (( cyc == cyc_fcst )); then
  export cycsuffix=false
  export fcstlong=true
else
  export fcstlong=false
  export cycsuffix=true
fi

echo fcstlong=$fcstlong
echo cycsuffix=$cycsuffix

####################################
# Specify NET and RUN Name and model
####################################
export NET=gens
export RUN=enstr

####################################
# File To Log Msgs
####################################
if [ "$RUN_ENVIR" = dev ]     ### For Developers
then
  export jlogfile=${jlogfile:-$baselog/com/logs/jlogfile}
else
  export jlogfile=/com/logs/para/jlogfile
fi

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# RMGES    - Clean Files in $GESdir
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SAVEGES=YES
export SENDSMS=YES
export SENDCOM=YES
export RERUN=NO
export VERBOSE=YES

###testb
if [[ $envir = prod ]]; then
###teste
 if [ $cyc -eq 00 -o $cyc -eq 12 ]
  then
   export SENDDBN=YES
  else
   export SENDDBN=YES
  fi
###testb
else
   export SENDDBN=YES
fi
###teste

 
####################################
# Specify Execution Areas
####################################
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
  export HOMEGSM=${HOMEGSM:-/nw${envir}}
  export EXECGSM=${EXECGSM:-$HOMEGSM/exec}
  export USHGSM=${USHGSM:-$HOMEGSM/ush}
  export FIXGSM=${FIXGSM:-$HOMEGSM/fix/fix_am}
  export PARMGSM=${PARMGSM:-$HOMEGSM/parm}

  export EXECGLOBAL=${EXECGSM:-$HOMEGSM/exec}
  export USHGLOBAL=${USHGSM:-$HOMEGSM/ush}
  export FIXGLOBAL=${FIXGSM:-$HOMEGSM/fix/fix_am}

# export HOMEGLOBAL=${HOMEGLOBAL:-/nw${envir}}
# export EXECGLOBAL=${EXECGSM:-$HOMEGSM/exec}
# export USHGLOBAL=${USHGSM:-$HOMEGSM/ush}
# export FIXGLOBAL=${FIXGSM:-$HOMEGSM/fix/fix_am}

  export HOMEgefs=${HOMEgefs:-/nw${envir}}
  export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
  export USHgefs=${USHgefs:-$HOMEgefs/ush}
  export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
  export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
  export USHGLOBAL=$USHgefs
  export EXECGLOBAL=$EXECGgefs

else                             ### For Operations

  export HOMEGSM=/nw${envir}
  export EXECGSM=$HOMEGSM/exec
  export USHGSM=$HOMEGSM/ush
  export FIXGSM=$HOMEGSM/fix/fix_am
  export PARMGSM=$HOMEGSM/parm

  export HOMEGLOBAL=/nwprod
  export EXECGLOBAL=$HOMEGSM/exec
  export USHGLOBAL=$HOMEGSM/ush
  export FIXGLOBAL=$HOMEGSM/fix/fix_am
  export PARMGLOBAL=$HOMEGSM/parm

  export HOMEGEFS=/nw${envir}
  export EXECGEFS=$HOMEGEFS/exec
  export USHGEFS=$HOMEGEFS/ush
  export FIXGEFS=$HOMEGEFS/fix
  export PARMGEFS=$HOMEGEFS/parm
fi



################# lines between these markers have been modified for dev end

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################################
echo set parameters using gefs.parm
##############################################

. $PARMgefs/gefs.parm
. $PARMgefs/gefs_init.parm

echo
env | sort
echo

##############################
# Set up the UTILITIES
##############################
export utilscript=$HOMEutil/ush
export EXECutil=$HOMEutil/exec


##############################
# Run setup to initialize working directory and utility scripts
##############################
sh $utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
sh $utilscript/setpdy.sh
. PDY

##############################################
# for global_chgres.sh
##############################################
#export SLMASK=/dev/null

##############################################
# Define COM directories
##############################################
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
export COMIN=$baseoutput/com/${NET}/${envir}/gefs.${PDY}
export COM=$baseoutput/com/${NET}/${envir}
export COMINm1=$baseoutput/com/${NET}/${envir}/gefs.${PDYm1}
export COMINm2=$baseoutput/com/${NET}/${envir}/gefs.${PDYm2}
export COMINm3=$baseoutput/com/${NET}/${envir}/gefs.${PDYm3}
export COMINm4=$baseoutput/com/${NET}/${envir}/gefs.${PDYm4}

export COMOUT=$baseoutput/com/${NET}/${envir}/gefs.${PDY}

else

export COMIN=/com/${NET}/${envir}/gefs.${PDY}
export COM=/com/${NET}/${envir}
export COMINm1=/com/${NET}/${envir}/gefs.${PDYm1}
export COMINm2=/com/${NET}/${envir}/gefs.${PDYm2}
export COMINm3=/com/${NET}/${envir}/gefs.${PDYm3}
export COMINm4=/com/${NET}/${envir}/gefs.${PDYm4}

export COMOUT=/com/${NET}/${envir}/gefs.${PDY}
fi

mkdir -m 775 -p $COMOUT/$cyc/init
mkdir -m 775 -p $COMOUT/$cyc/sflux

##############################################
# Define GES directories
##############################################
if [ "$RUN_ENVIR" = dev ]         ### For Developers
then
gespath=$baseoutput/nwges/${envir}
else
gespath=/nwges/${envir}
fi
export GESdir=$gespath/gefs.${PDY}
mkdir -m 775 -p $GESdir

##############################################
echo list environment before running script
##############################################

echo
env | sort
echo

#############################################################
# Execute the script
$HOMEgefs/scripts/exgefs_init_combine.sh.ecf
#############################################################

cat $pgmout

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the working directory
##############################
###testb
if [[ $envir = prod ]]; then
###teste
cd /tmpnwprd
rm -rf $DATA
###testb
elif [[ $envir = para ]] || \
     [[ $envir = test ]]; then
cd /tmpnwprd
#rm -rf $DATA
else
  echo skip cleanup for testing
################# lines between these markers have been modified for dev begin
  echo `date` special copy begin
  if [[ $envir = dev ]]; then
    ##################################### parameter controlled copy to mirror
    if [[ x$initarchlist != x ]]; then
      iafound=no
      for cyctest in $initarchlist
      do
        if (( cyc == cyctest )); then
          diro=$baseinitarch/nwges/$envir/gefs.$PDY
          diri=$baseoutput/nwges/$envir/gefs.$PDY
          if [[ -d $diri ]]; then
            cd $diri
            rc=$?
            if (( rc == 0 )); then
              rctot=0
              mkdir -p $diro
              if [[ -d $diro ]]; then
                for file in *.t${cyc}z.sanl* gec00.t${cyc}z.sfcanl
                do
                  if [[ -f $file ]]; then
                    ls -al $file
                    cp -p $file $diro/$file
                    rc=$?
                    if (( rc == 0 )); then
                      ls -al $diro/$file
                    else
                      (( rctot = rctot + rc ))
                      echo cp -p $file $diro/$file FAILED rc=$rc
                    fi
                  else
                    echo file=$file DOES NOT EXIST AS A FILE IN $diro
                    (( rctot = rctot + 10000 ))
                  fi
                done
                if (( rctot != 0 )); then
                  echo special copy guess files FAILED rctot=$rctot
                fi
                found=yes
              else
                echo diro=$diro DOES NOT EXIST AS A DIRECTORY
              fi
            else
              echo cd $diri FAILED rc=$rc
            fi
          else
            echo diri=$diri DOES NOT EXIST AS A DIRECOTRY
          fi
        fi
      done
      if [[ iafound = no ]]; then
        echo special copy not done because cyc=$cyc is not in initarchlist=$initarchlist
      fi
    else
      echo special copy not done because initarchlist=$initarchlist is not defined
    fi
  else
    echo special copy not done because envir=$envir
  fi
  echo `date` special copy tests end
################# lines between these markers have been modified for dev end
fi
###teste

echo `date` $0 `date -u` end
###testb
if [[ $envir = prod ]] || \
   [[ $envir = para ]] || \
   [[ $envir = test ]]; then
###teste
$SMSBIN/endt
###testb
else
  echo skip endt for testing
fi
###teste
