#!/bin/bash

echo `date` $0 `date -u` begin

set -xa
export PS4=' $SECONDS + '
date

export NTASKS=${total_tasks:-20}

############################
# Set up cycle varaible
############################
cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}

####################################
# obtain unique process id (pid) and make working directory
####################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gwes}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export MP_PULSE=0

####################################
# Path to HOME Directory
####################################
export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export HOMEgfs=${HOMEgfs:-$HOMEgefs}

export HOMEwave=${HOMEwave:-${HOMEgefs}}
export EXECwave=${EXECwave:-$HOMEwave/exec}
export FIXwave=${FIXwave:-$HOMEwave/fix/fix_wave}
export PARMwave=${PARMwave:-$HOMEwave/parm}
export USHwave=${USHwave:-$HOMEwave/ush}

export EXECcode=${EXECcode:-$EXECwave}

##############################################
# Set parameters using gwes_post.parm
##############################################

. $PARMgefs/gefs.parm
. $PARMgefs/gwes.parm
. $PARMwave/gwes_post.parm

###################################
# Create and go to DATA directory
#  (requires wavemodTAG) 
###################################
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA

# Set PDY
setpdy.sh
sh ./PDY

# Set wave model ID tag to include member number 
# if ensemble; waveMEMB var empty in deterministic
membTAG='p'
if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
export membTAG
export wavemodTAG=${wavemodID}${waveMEMB}

###################################
# Set COM Paths and GETGES environment
###################################

export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${RUN}.${PDY}/${cyc}}
export COMOUT=${COMOUT:-${COMOUTwave}/${RUN}.${PDY}/${cyc}}

export COMICE=${COMICE:-${COMROOT}/omb/prod}
export COMWND=${COMWND:-${COMROOT}/gfs/prod}
export COMCUR=${COMCUR:-${COMROOT}/rtofs/prod}

if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT/gridded
  mkdir -p $COMOUT/station
  mkdir -p $COMOUT/stats
fi

export wavelog=${COMOUTwave}/wave.log

##################################
# Set mpi serial command
#################################
export wavempexec=${wavempexec:-"mpirun"}
export wave_mpmd=${wave_mpmd:-"cfp"}

env | sort

###################################
# Execute the Script  
###################################

$HOMEwave/scripts/exwave_gwes_post.sh
err=$?
if [ $err -ne 0 ]; then
    msg="FATAL ERROR: ex-script of GWES_POST failed!"
else
    msg="$job completed normally!"
fi
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

exit $err
