#!/bin/bash

date
export PS4=' $SECONDS + '
set -x

# PATH for working directory
export NET=${NET:-gens}
export RUN=${RUN:-gwes}

export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export HOMEgsm=${HOMEgsm:-$NWROOT/gsm.${gsm_ver}}

# Set HOMEwave to HOMEgefs
HOMEwave=${HOMEwave:-${HOMEgefs}} 

export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA

cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}
 
export pgmout=OUTPUT.$$

export MP_PULSE=0

####################################
# Path to HOME Directory
####################################

export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${code_pkg}}

export EXECwave=${EXECwave:-$HOMEwave/exec}
export FIXwave=${FIXwave:-$HOMEwave/fix_wave}
export PARMwave=${PARMwave:-$HOMEwave/parm}
export USHwave=${USHwave:-$HOMEwave/ush}
export EXECcode=${EXECcode:-$CODEwave/exec}

# Set PDY
setpdy.sh
sh ./PDY

###################################
# Set COM Paths and GETGES environment
###################################

export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${RUN}.${PDY}/${cyc}}
export COMOUT=${COMOUT:-${COMOUTwave}/${RUN}.${PDY}/${cyc}}

export COMICE=${COMICE:-${COMROOTp2}/omb/prod}
export COMWND=${COMWND:-${COMROOT}/gfs/prod}
export COMCUR=${COMCUR:-${COMROOTp2}/rtofs/prod}

if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT
fi

export wavelog=${COMOUTwave}/wave.log

##############################################
 Set parameters using gwes_post.parm
##############################################

. $PARMwave/gwes.parm
. $PARMwave/gwes_post.parm

env | sort

##################################
# Set mpi serial command
#################################
export gwesmpexec_mpmd=${gwesmpexec_mpmd:-"mpirun.lsf cfp cmdfile"}

###################################
# Execute the Script  
###################################

$HOMEwave/scripts/exwave_gwes_post.sh

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

