#!/bin/bash

date
export PS4=' $SECONDS + '
set -x -e

# PATH for working directory
export NET=${NET:-gens}
export RUN=${RUN:-gwes}

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA

cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}
 
export pgmout=OUTPUT.$$

export MP_PULSE=0

####################################
# Path to HOME Directory
####################################
export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export HOMEgsm=${HOMEgsm:-$HOMEgefs}
export HOMEgfs=$HOMEgsm

export HOMEwave=${HOMEwave:-${HOMEgefs}}
export EXECwave=${EXECwave:-$HOMEwave/exec}
export FIXwave=${FIXwave:-$HOMEwave/fix/fix_wave}
export PARMwave=${PARMwave:-$HOMEwave/parm}
export USHwave=${USHwave:-$HOMEwave/ush}

export EXECcode=${EXECcode:-$EXECwave}

# Set PDY
setpdy.sh
sh ./PDY

###################################
# Set COM Paths and GETGES environment
###################################

export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${RUN}.${PDY}/${cyc}}
export COMOUT=${COMOUT:-${COMOUTwave}/${RUN}.${PDY}/${cyc}}

if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT/rundata
fi

export wavelog=${COMOUTwave}/wave.log

##################################
# Set mpi serial command
#################################
export wavempexec=${wavempexec:-"mpirun"}
export wave_mpmd=${wave_mpmd:-"cfp"}

##############################################
# Set parameters using gwes_init.parm
##############################################

. $PARMgefs/gefs.parm
. $PARMwave/gwes.parm
. $PARMwave/gwes_init.parm

env | sort

###################################
# Execute the Script  
###################################

$HOMEwave/scripts/exwave_gwes_init.sh
err=$?
if [ $err -ne 0 ]; then
    msg="FATAL ERROR: ex-script of GWES_INIT failed!"
else
    msg="$job completed normally!"
fi
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

exit $err
