#!/bin/bash

date
export PS4=' $SECONDS + '
set -x

# PATH for working directory
export NET=${NET:-wave}
export RUN=${RUN:-gwes}
HOMEwave=${HOMEwave:-$(dirname $(dirname $0))} # parent directory of current job card

export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA

cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}
 
export pgmout=OUTPUT.$$

export MP_PULSE=0

####################################
# Path to HOME Directory
####################################

export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${code_pkg}}

export EXECwave=$HOMEwave/exec
export FIXwave=$HOMEwave/fix
export PARMwave=$HOMEwave/parm
export USHwave=$HOMEwave/ush
export EXECcode=$CODEwave/exec

# Set PDY
setpdy.sh
sh ./PDY

###################################
# Set COM Paths and GETGES environment
###################################

export COMICE=${COMICE:-${COMROOTp2}/omb/prod}

export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMOUTwave}/${RUN}.${PDY}}

if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT
fi

export wavelog=${COMOUTwave}/wave.log

##############################################
 Set parameters using gwes_prep.parm
##############################################

. $PARMgefs/gwes_prep.parm

env | sort

###################################
# Execute the Script  
###################################

$HOMEwave/scripts/exwave_gwes_prep.sh

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

