#!/bin/bash

date
export PS4=' $SECONDS + '
set -x

# PATH for working directory
export NET=${NET:-wave}
export RUN=${RUN:-multi_1}
HOMEwave=${HOMEwave:-$(dirname $(dirname $0))} # parent directory of current job card

export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA

cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}
 
export pgmout=OUTPUT.$$

export MP_PULSE=0

export modID=${modID:-multi_1}
export sigMODE=${sigMODE:-prep}

####################################
# Path to HOME Directory
####################################

export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${code_pkg}}

export EXECwave=$HOMEwave/exec
export FIXwave=$HOMEwave/fix
export PARMwave=$HOMEwave/parm
export USHwave=$HOMEwave/ush
export EXECcode=$CODEwave/exec

export GETGES=${NWROOTprod:?}/util/ush/getges.sh

# Set PDY
setpdy.sh
sh ./PDY

###################################
# Set COM Paths and GETGES environment
###################################

export COMGFS=${COMGFS:-${COMROOThps}/gfs/prod}
export COMINgdas=${COMINgdas:-${COMGFS}/gdas.${PDY}/${cyc}}
export COMINgfs=${COMINgfs:-${COMGFS}/gfs.${PDY}/${cyc}}
export COMICE=${COMICE:-${COMROOTp2}/omb/prod}
export COMSST=${COMSST:-${COMROOTp2}/gfs/prod}
export GETGES_envr=${GETGES_envr:-prod}

export COMINwave=${COMINwave:-${COMROOT:?}/${NET}/${envir}}
export COMOUTwave=${COMOUTwave:-${COMROOT:?}/${NET}/${envir}}
export COMIN=${COMIN:-${COMINwave}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMOUTwave}/${RUN}.${PDY}}

if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT
fi

export wavelog=${COMOUTwave}/wave.log

env

###################################
# Execute the Script  
###################################

$HOMEwave/scripts/exwave_multi_1_prep.sh.ecf

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

