#!/bin/sh
#
# rename the output for a particular date of GEFS run
#
echo `date` $0 $* begin
if (( $# == 3 )); then
  expid=$1
  yyyymmdd=$2
  dtg=$2
  suffix=$3
  echo expid=$expid yyyymmdd=$yyyymmdd suffix=$suffix
  if (( dtg < 23010203 )) && (( dtg > 18010203 )); then
    controldir=/ensemble/save/$LOGNAME/s/$expid/nwdev/control
    cd $controldir
    rc=$?
    if (( rc == 0 )); then
      dirlist="
	/ptmp/$LOGNAME/o/$expid/com/output/dev/$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/com/gens/dev/gefs.$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/nwdev/control/$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/nwges/dev/gefs.$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/tmpnwprd \
      "

      suffixused=no
      for dir in $dirlist
      do
        if [[ -d $dir.$suffix ]]; then
          suffixused=yes
          ls -ald $dir.$suffix
        fi
      done

      if [[ $suffixused = no ]]; then
	waitno
	for dir in $dirlist
	do
	  if [[ -d $dir ]]; then
	    ls -ald $dir
	    mv $dir $dir.$suffix
	    ls -ald $dir.$suffix
	  else
	    echo dir=$dir DOES NOT EXIST
	  fi
	done
      else
        echo suffix $suffix IS ALREADY IN USE
      fi
    else
      echo cd $controldir FAILED rc=$rc
    fi
  elif (( dtg < 2301020318 )) && (( dtg > 1801020300 )); then
    yyyymmdd=`echo $dtg|cut -c1-8`
    hh=`echo $dtg|cut -c9-10`
    controldir=/ensemble/save/$LOGNAME/s/$expid/nwdev/control
    cd $controldir
    rc=$?
    if (( rc == 0 )); then
      dirlist="
	/ptmp/$LOGNAME/o/$expid/com/output/dev/$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/com/gens/dev/gefs.$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/nwdev/control/$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/nwges/dev/gefs.$yyyymmdd \
	/ptmp/$LOGNAME/o/$expid/tmpnwprd \
      "

      suffixused=no
      for dir in $dirlist
      do
        if [[ -d $dir.$suffix ]]; then
          suffixused=yes
          ls -ald $dir.$suffix
        fi
      done

      if [[ $suffixused = no ]]; then
	waitno
	for dir in $dirlist
	do
	  if [[ -d $dir ]]; then
	    ls -ald $dir
            dirz=`dirname $dir`
            diry=`dirname $dirz`
            dirx=`basename $diry`
	    diro=$dir.$suffix
            echo dirx=$dirx $diro=$diro
            case $dirx in
	      (output)
	        mkdir -p $diro
		rc=$?
		if (( rc == 0 )); then
		  for file in $dir/??$yyyymmdd${hh}???.*.o
		  do
		    if [[ -f $file ]]; then
		      mv $file $diro
		    else
		      echo file=$file DOES NOT EXIST AS A FILE IN $dir
		    fi
		  done
		else
		  echo mkdir -p $diro FAILED rc=$rc
		fi
	      ;;
	      (gens)
	        mkdir -p $diro
		rc=$?
		if (( rc == 0 )); then
		  if [[ -d $dir/$hh ]]; then
		    mv $dir/$hh $diro/$hh
		  else
		    echo hh=$hh DOES NOT EXIST AS A DIRECTORY IN $dir
		  fi
		else
		  echo mkdir -p $diro FAILED rc=$rc
		fi
	      ;;
	      (nwdev)
	        mkdir -p $diro
		rc=$?
		if (( rc == 0 )); then
		  if [[ -d $dir/$hh ]]; then
		    mv $dir/$hh $diro/$hh
		  else
		    echo hh=$hh DOES NOT EXIST AS A DIRECTORY IN $dir
		  fi
		else
		  echo mkdir -p $diro FAILED rc=$rc
		fi
	      ;;
	      (nwges)
	        mkdir -p $diro
		rc=$?
		if (( rc == 0 )); then
		  for file in $dir/*.t${hh}z.*
		  do
		    if [[ -f $file ]]; then
		      mv $file $diro
		    else
		      echo file=$file DOES NOT EXIST AS A FILE IN $dir
		    fi
		  done
		else
		  echo mkdir -p $diro FAILED rc=$rc
		fi
	      ;;
	      (o)
	        mv $dir $diro
	      ;;
	      (*)
	        echo THERE IS NO COPY PROCESS DEFINED FOR dirx=$dirx dir=$dir
	      ;;
            esac
	    ls -ald $dir $diro
	  else
	    echo dir=$dir DOES NOT EXIST
	  fi
	done
      else
        echo suffix $suffix IS ALREADY IN USE
      fi
    else
      echo cd $controldir FAILED rc=$rc
    fi
  else
    echo dtg=$dtg IS OUT OF RANGE
  fi
else
  echo 3 arguments required: expid YYYYMMDD suffix
fi
echo `date` $0 $* end

