#!/bin/sh
#
# set up base variables
# execute with dot
#
echo
echo `date` $0 $* setbase begin
echo

echo
echo `date` $0 set environment and experiment id
echo

#envir=$(basename $(dirname $(pwd) ) | cut -c3-)
echo envir=$envir

#expid=$(basename $(dirname $(dirname $(pwd) ) ) )
#id=`echo $expid|cut -c3-4`
echo expid=$expid
echo id=$id

echo
echo `date` $0 set directory tree locations
echo

if [[ $LOGNAME = glopara ]]; then
  echo
  echo directory locations for running in glopara account
  echo using codes and scripts in $LOGNAME account
  echo

  export basesource=/global/save/wx20rw/s/$expid
  export baseoutput=/ptmp/$LOGNAME/para_gefs/o/$expid

  export basetmp=/ptmp/$LOGNAME/para_gefs/o/$expid
  export baseptmp=/ptmp/$LOGNAME/para_gefs/o/$expid
  export basebin=$basesource/nw$envir/control

  export baselog=/global/noscrub/$LOGNAME/para_gefs/o/$expid
  export basedgfs=/global/noscrub/$LOGNAME/para_gefs/o/$expid
  export basedgens=/ptmp/$LOGNAME/para_gefs/o
  export baseinitarch=/global/mirror/$LOGNAME/para_gefs/o/$expid

  export account=GEN-T2O
  export group=devonprod
  export classs=1
  export classp=devhigh
  export classp=dev
else
  echo
  echo directory locations for running in $LOGNAME account
  echo

  export basesource=/global/save/$LOGNAME/s/$expid
  export baseoutput=/ptmp/$LOGNAME/o/$expid

# For VAPOR
# PTMP=/ptmp/$LOGNAME/tskh
# PTMP=/gpfs/v3/benchmark/wx15dp/wx20dh/tskh
# PGFS=/gpfs/v/mtb/noscrub/$LOGNAME/TSKH/GFS

# export basesource=/gpfs/v/mtb/save/$LOGNAME/tskh/$expid
# export baseoutput=$PTMP/o/$expid
# For VAPOR end

  export basetmp=/ptmp/$LOGNAME/o/$expid
  export baseptmp=/ptmp/$LOGNAME/o/$expid
# For VAPOR
# export basetmp=$PTMP/o/$expid
# export baseptmp=$PTMP/o/$expid
# For VAPOR end
  export basebin=$basesource/nw$envir/control

  export baselog=/ptmp/$LOGNAME/o/$expid
  export basedgfs=/global/noscrub/$LOGNAME/o
  export basedgens=/ptmp/$LOGNAME/o
  export baseinitarch=/global/mirror/$LOGNAME/o/$expid

# For VAPOR
# export baselog=$PTMP/o/$expid
# export basedgfs=$PGFS/o
# export basedgens=$PTMP/o
# For VAPOR end

  export account=GEN-T2O
  export group=g01
  export group=devonprod
  export classs=1
  export classp=dev
  export classp=devhigh
# For VAPOR
# export account=MTB001-RES
# export group=mtb
# export classs=1
# export classp=mtb
# export classp=mtb
# For VAPOR end
fi

echo basesource=$basesource
echo baseoutput=$baseoutput
echo
echo basetmp=$basetmp
echo baseptmp=$baseptmp
echo basebin=$basebin
echo
echo basedgfs=$basedgfs
echo basedgens=$basedgens
echo
echo account=$account
echo group=$group
echo classs=$classs
echo classp=$classp
echo
echo `date` $0 $* setbase end
echo
