#!/bin/ksh
#
# set waitfile file to no
#
echo `date` $0 $* begin

machl=`uname -n|cut -c1`

echo waitfile.$machl before
cat waitfile.$machl
echo no>waitfile.$machl
echo waitfile.$machl after
cat waitfile.$machl

echo `date` $0 $* end

