#!/bin/ksh
#
# set up base variables
# execute with dot
#
echo
echo `date` $0 $* setbase begin
echo

echo
echo `date` $0 set environment and experiment id
echo

#DHOU, 01/03/2013 add this block to generate the machine name related variables
machl=`uname -n | cut -c1`

if [[ $machl = r ]]; then
  machl=f
fi
if [[ $machl = n ]]; then
  machl=l
fi

#envir=$(basename $(dirname $(pwd) ) | cut -c3-)
echo envir=$envir

#expid=$(basename $(dirname $(dirname $(pwd) ) ) )
echo expid=${expid}

id=`echo $expid|cut -c3-4`
echo expid=$expid
echo id=$id

echo
echo USER to prescribe user ID and JOB queue infirmation
echo
PROJECT=ensemble
LOGNAME=$LOGNAME
SUBNAME=
JOBPRIO=      
JOBQUEUE=dev
JOBPHASE=
#Please make sure you have the correct account information
export account=GEN-T2O

if [[ "$LOGNAME" = "emc.enspara" || "$LOGNAME" = "emc.enspara1" ]]; then
	SUBNAME=/XX    #members of the enspara/enspara1 group accounts need to define e.g SUBNAME=/dc
	JOBPRIO=high       #(default; it could be high/max)
fi

echo USER info: $PROJECT $LOGNAME $SUBNAME $JOBPRIO

echo JOB QUEUE info prescribed: $JOBQUEUE $JOBPHASE $JOBPRIO

echo ACCOUNT info: $account

echo
echo `date` $0 set ROOT directory tree locations
echo

if [ -d /scratch4/NCEPDEV ]; then 
	echo "Using settings for Theia"
	PTMP=/scratch4/NCEPDEV/stmp4
	STMP=/scratch4/NCEPDEV/stmp4
	SAVE=/scratch4/NCEPDEV/ensemble/save
	NOSCRUB=/scratch4/NCEPDEV/ensemble/noscrub
	export machine='THEIA'
	export JOBPHASE=
	#export HOMEDIR=/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/fv3gfs
	#export HOMEDIR1=/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/fv3gfs
	#export HOMERFC=/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/ens_tracker

	export HOMEDIR=/scratch4/NCEPDEV/ensemble/save/Xianwu.Xue/GIT/fv3gfs # this is the master branch with Bing Fu's modification based on the GEFS needs
	export HOMEDIR1=$HOMEDIR 						#/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/fv3gfs
	export HOMERFC=/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/ens_tracker

	#export KMP_AFFINITY=scatter

	# export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/common
	#export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/Walter.Kolczynski/nemsio_init
 	#export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/Bing.Fu/fv3gefs_init
    export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/Xianwu.Xue/fv3gefs_init
	export HOMEdata=${COMROOThps} 

	export EXECutil=${EXECutil:-/scratch4/NCEPDEV/global/save/glopara/nwpara/util/exec}
	export USHutil=${USHutil:-/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/nwprod/util/ush}

	export PATH=$PATH:$USHutil:$EXECutil

	export EXECgrib=${EXECutil}
	export NDATE=${NDATE:-$EXECgrib/ndate}
	export utilscript=$USHutil

	# For SST - However, for CRAY, it has  the default value
    export CFSv2_clim_dir=${CFSv2_clim_dir:-/scratch4/NCEPDEV/ensemble/noscrub/Xianwu.Xue/svn/DATA/subx/CFS_ANOM2_create_Eric_0p25/CFSv2_clim}
    export climogb2trim=${climogb2trim:-/scratch4/NCEPDEV/ensemble/noscrub/Xianwu.Xue/svn/DATA/subx/CFS_ANOM2_create_Eric_0p25/CFSR_clim/tmpsfc.cfsr.mean.clim.daily.1999.2010.grb2}

	#export USHutil=/scratch3/NCEPDEV/nwprod/util/exec for ndate
	#export EXECgrib=/scratch3/NCEPDEV/nwprod/grib_util.v1.0.5/exec

	#export HOMEgsm=$HOMEDIR/global_shared.v15.0.0
	#export HOMEgsm1=$HOMEDIR1/global_shared.v15.0.0
	#export FCSTEXECDIR=$HOMEgsm/sorc/fv3gfs.fd/NEMS/exe
	#export nemsioget=$HOMEgsm/exec/nemsio_get

	# No program use it.
	#export memdir_template='$ROTDIR/enkf.$CDUMP.$PDY/$cyc'

	#export HOMEenkf=$HOMEgsm/sorc/gsi.fd
	#export HOMEpost=$HOMEgsm/sorc/upp.fd

	# It seems that no program uses  these two variables
	#export I_MPI_EXTRA_FILESYSTEM=on
	#export I_MPI_EXTRA_FILESYSTEM_LIST=lustre:panfs

	#export chgresush=$HOMEgsm1/ush/global_chgres_GSM.sh
	# if need, we can use : export chgresush=$HOMEDIR/ush/global_chgres.sh

	#export CHGRESEXEC=$HOMEgsm1/exec/global_chgres_GSM
	#export CHGRESEXEC=$HOMEDIR/exec/global_chgres

	#export DIAG_TABLE=$HOMEgsm/parm/parm_fv3diag/diag_table
	#export FIELD_TABLE=$HOMEgsm/parm/parm_fv3diag/field_table_gfdl

	#export WGRIB2=${WGRIB2:-wgrib2}
	#export GRB2INDEX=${GRB2INDEX:-/scratch3/NCEPDEV/nwprod/NWPROD.WCOSS/util/exec/grb2index}
	#export COPYGB2=${COPYGB2:-/scratch3/NCEPDEV/nwprod/NWPROD.WCOSS/util/exec/copygb2}

	

elif [ -d /gpfs/hps3 ]; then

	if [[ $machl = t ]] || [[ $machl = g ]]; then
		"Using settings for WCOSS Phase II"
		PTMP=/ptmpd2
		STMP=/stmpd2
		export machine='WCOSS'
		export JOBPHASE=2
		export HOMEDIR=/ensemble/save/emc.enspara/RFC
		#export HOMEDIR1=/ensemble/save/emc.enspara/RFC/q3fy17_lambda
		SAVE=/$PROJECT/save
		NOSCRUB=/$PROJECT/noscrub

	elif [[ $machl = s ]] || [[ $machl = l ]]; then
		echo "Using settings for WCOSS Cray"
		PTMP=/gpfs/hps/ptmp
		STMP=/gpfs/hps2/stmp
		export machine='WCOSS_C'
		export JOBPHASE=
		#export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/svn/fv3gfs20180204  #temporay setting
		#export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/Xiaqiong.Zhou/git_gfs/fv3gfs/tic21f  # Kate, cold start before 5/9
#		export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/Bing.Fu/svn/tic21f      #Bing Fu warm start after 5/9
#		export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/Bing.Fu/svn/fy2019q1      # most recent fv3gfs upon 5/15/2018
		export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/svn/fy2019q2      # most recent fv3gfs upon 5/15/2018
		export HOMEDIR1=/gpfs/hps3/emc/ensemble/save/emc.enspara/RFC/q3fy17_lambda
		export HOMERFC=/gpfs/hps3/emc/ensemble/save/emc.enspara/RFC
		SAVE=/gpfs/hps3/emc/$PROJECT/save
		NOSCRUB=/gpfs/hps3/emc/$PROJECT/noscrub
	fi
fi

export JOBQUEUE=$JOBQUEUE$JOBPRIO$JOBPHASE
echo JOB QUEUE info: $JOBQUEUE 

echo ROOT DIRECTORY info:
echo $machine  jobqueue=$JOBQUEUE
echo ptmp: $PTMP
echo stmp: $STMP
echo save: $SAVE
echo noscrub: $NOSCRUB
echo homedir: $HOMEDIR

echo
echo `date` $0 setuser base directory tree locations
echo

#export basesource=$SAVE/$LOGNAME$SUBNAME/GEFS/$expid
#export basebin=$basesource/nw$envir/control
export basesource=$SOURCEDIR
export baseoutput=$WORKDIR

echo USER BASE DIRECTORY info:
echo SOURCE: $basesource
echo BIN: $basebin
echo OUT: $baseoutput

echo
echo `date` $0 $* setbase end
echo
