#!/bin/ksh
#
# set up base variables
# execute with dot
#
echo
echo `date` $0 $* setbase begin
echo

echo
echo `date` $0 set environment and experiment id
echo

#DHOU, 01/03/2013 add this block to generate the machine name related variables
machl=`uname -n | cut -c1`

if [[ $machl = r ]]; then
  machl=f
fi
if [[ $machl = n ]]; then
  machl=l
fi

#envir=$(basename $(dirname $(pwd) ) | cut -c3-)
echo envir=$envir

#expid=$(basename $(dirname $(dirname $(pwd) ) ) )
echo expid=${expid}

id=`echo $expid|cut -c3-4`
echo expid=$expid
echo id=$id

echo
echo USER to prescribe user ID and JOB queue infirmation
echo
PROJECT=ensemble
LOGNAME=$LOGNAME
SUBNAME=
JOBPRIO=      
JOBQUEUE=dev
JOBPHASE=
#Please make sure you have the correct account information
export account=GEN-T2O

if [[ "$LOGNAME" = "emc.enspara" || "$LOGNAME" = "emc.enspara1" ]]; then
    SUBNAME=/XX    #members of the enspara/enspara1 group accounts need to define e.g SUBNAME=/dc
    JOBPRIO=high       #(default; it could be high/max)
fi

echo USER info: $PROJECT $LOGNAME $SUBNAME $JOBPRIO

echo JOB QUEUE info prescribed: $JOBQUEUE $JOBPHASE $JOBPRIO

echo ACCOUNT info: $account

echo
echo `date` $0 set ROOT directory tree locations
echo

if [ -d /scratch4/NCEPDEV ]; then 
	echo "Using settings for Theia"
	PTMP=/scratch4/NCEPDEV/stmp4
	STMP=/scratch4/NCEPDEV/stmp4
	SAVE=/scratch4/NCEPDEV/ensemble/save
	NOSCRUB=/scratch4/NCEPDEV/ensemble/noscrub
	export machine='THEIA'
    
	export HOMEDIR=/scratch4/NCEPDEV/ensemble/noscrub/common/fv3gfs/fv3gfs_ens_20180814
	export HOMEDIR1=$HOMEDIR 						#/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/fv3gfs
	export HOMERFC=/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/ens_tracker

	#export KMP_AFFINITY=scatter

	# export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/common
	#export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/Walter.Kolczynski/nemsio_init
 	#export COMROOThps=/scratch4/NCEPDEV/ensemble/noscrub/Bing.Fu/fv3gefs_init
    export HOMEdata=/scratch4/NCEPDEV/ensemble/noscrub/common
    export COMROOThps=${HOMEdata} 

    export EXECutil=${EXECutil:-/scratch4/NCEPDEV/global/save/glopara/nwpara/util/exec}
    export USHutil=${USHutil:-/scratch4/NCEPDEV/ensemble/save/Walter.Kolczynski/nwprod/util/ush}

    export PATH=$PATH:$USHutil:$EXECutil

    export EXECgrib=${EXECutil}
    export NDATE=${NDATE:-$EXECgrib/ndate}
    export utilscript=$USHutil

elif [ -d /gpfs/hps3 ]; then

    if [[ $machl = t ]] || [[ $machl = g ]]; then
        echo "Using settings for WCOSS Phase II"
        PTMP=/ptmpd2
        STMP=/stmpd2
        export machine='WCOSS'
        export JOBPHASE=2
        # export HOMEDIR=/ensemble/save/Walter.Kolczynski/fv3gfs/fv3gfs_ens_20180814
        export HOMEDIR=/ensemble/save/Walter.Kolczynski/fv3gfs/20181004_c550fea3
        export HOMEDIR1=$HOMEDIR
        export HOMERFC=/gpfs/hps3/emc/ensemble/save/emc.enspara/RFC
		
		export HOMEdata=/ensemble/noscrub/Walter.Kolczynski/gefs_input/gfs_15_para
		export COMINenkf_base=$HOMEdata/enkf.gdas.
		export COMINgfs_base=$HOMEdata/gfs.
		export COMINcfs_base=/ensemble/noscrub/Walter.Kolczynski/gefs_input/cfs_2_sst/cfs.
		export COMROOThps=${HOMEdata}
		export CHGRESEXEC=$HOMEDIR/exec/chgres_recenter.exe

        SAVE=/$PROJECT/save
        NOSCRUB=/$PROJECT/noscrub

    elif [[ $machl = s ]] || [[ $machl = l ]]; then
        echo "Using settings for WCOSS Cray"
        PTMP=/gpfs/hps/ptmp
        STMP=/gpfs/hps2/stmp
        export machine='WCOSS_C'
        export JOBPHASE=
        #export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/svn/fv3gfs20180204  #temporay setting
        #export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/Xiaqiong.Zhou/git_gfs/fv3gfs/tic21f  # Kate, cold start before 5/9
#       export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/Bing.Fu/svn/tic21f      #Bing Fu warm start after 5/9
#       export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/Bing.Fu/svn/fy2019q1      # most recent fv3gfs upon 5/15/2018
        #export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/svn/fy2019q2      # most recent fv3gfs upon 5/15/2018
        export HOMEDIR=/gpfs/hps3/emc/ensemble/noscrub/emc.enspara/svn/fv3gfs
        export HOMEDIR1=/gpfs/hps3/emc/ensemble/save/emc.enspara/RFC/q3fy17_lambda
        export HOMERFC=/gpfs/hps3/emc/ensemble/save/emc.enspara/RFC
        SAVE=/gpfs/hps3/emc/$PROJECT/save
        NOSCRUB=/gpfs/hps3/emc/$PROJECT/noscrub
    fi
fi

export JOBQUEUE=$JOBQUEUE$JOBPRIO$JOBPHASE
echo JOB QUEUE info: $JOBQUEUE 

echo ROOT DIRECTORY info:
echo $machine  jobqueue=$JOBQUEUE
echo ptmp: $PTMP
echo stmp: $STMP
echo save: $SAVE
echo noscrub: $NOSCRUB
echo homedir: $HOMEDIR

echo
echo `date` $0 setuser base directory tree locations
echo

#export basesource=$SAVE/$LOGNAME$SUBNAME/GEFS/$expid
#export basebin=$basesource/nw$envir/control
export basesource=$SOURCEDIR
export baseoutput=$WORKDIR

echo USER BASE DIRECTORY info:
echo SOURCE: $basesource
echo BIN: $basebin
echo OUT: $baseoutput

echo
echo `date` $0 $* setbase end
echo
