#!/bin/ksh
#
#BSUB -J zs2012102200301.130226133649
#BSUB -o /ptmp/Richard.Wobus/o/rwzs/com/output/dev/20121022/zs2012102200301.130226133649.o
#BSUB -e /ptmp/Richard.Wobus/o/rwzs/com/output/dev/20121022/zs2012102200301.130226133649.o
#BSUB -W 1:30
#BSUB -q "hpc_ibm" 
##BSUB -q "dev" 
#BSUB -L /bin/ksh
#
#
##BSUB -l mem=1000M
module load ics
echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev begin
echo `date` env sort begin
env | sort
echo `date` env sort end

export envir=dev
export cyc=00
export cyc_fcst=00
export job=zs2012102200301
export RUN=gep20
export FORECAST_SEGMENT=lr
# export for development runs only begin
pwdsave=$(pwd)
echo $pwdsave
cd /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control
. /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control/setbase
. /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/parm/gefs.parm
cd 
export RUN_ENVIR=dev
export gefsmachine=wcoss
export gefsmpexec=mpirun.lsf
export jjj=301
export jjje=999
export yyyymmddcc=2012102200
export yyyymmddcce=2012102200
export yyyymmddccjjj=2012102200301
export yyyymmddccjjje=2012102200999
# export yyyymmddccc  #DHOU, 09/09/2010 ad this to facilitate job 000
# RLW disabled since the copy of initial conditions is moved into this script
#if (( jjj == 000 )); then
#  export yyyymmddccc=2012102200
#fi
export PDYp2=20121024
export PDYp1=20121023
export PDY=20121022
export PDYm1=20121021
export PDYm2=20121020
export PDYm3=20121019
export PDYm4=20121018
export PDYm5=20121017
export id=zs
export expid=rwzs
export basesource=/ensemble/save/Richard.Wobus/WCOSS/rwzs
export baseoutput=/ptmp/Richard.Wobus/o/rwzs
export baseinitarch=/global/mirror/Richard.Wobus/o/rwzs
export basetmp=/ptmp/Richard.Wobus/o/rwzs
export baseptmp=/ptmp/Richard.Wobus/o/rwzs
export basebin=/global/save/Richard.Wobus/s/rwzs/nwdev/control
export baselog=/ptmp/Richard.Wobus/o/rwzs
export basedgfs=
export basedgens=/ptmp/Richard.Wobus/o
echo `date` env sort begin
env | sort
echo `date` env sort end
# export for development runs only end

pwdsave=`pwd`

echo `date` ./gefsrun 2012102200301 2012102200999 next submit for dev before begin

cd /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control
./gefsrun 2012102200301 2012102200999 nextbefore 2>&1
rc=$?
echo `date` ./gefsrun 2012102200301 2012102200999 nextbefore rc=$rc
cd $pwdsave
echo `date` ./gefsrun 2012102200301 2012102200999 next submit for dev before end

echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev run before

echo
ls -al /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev
echo

# CALL executable job script here
/ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev

echo
ls -al /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev
echo

echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev run after

echo `date` ./gefsrun  2012102200301 2012102200999 next submit for dev after begin

cd /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control
./gefsrun 2012102200301 2012102200999 nextafter 2>&1
rc=$?
echo `date` ./gefsrun 2012102200301 2012102200999 nextafter rc=$rc

cd $pwdsave
echo `date` ./gefsrun  2012102200301 2012102200999 next submit for dev after end

echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/jobs/JGEFS_RESTART_COPY.sms.dev end
echo `date` test output files begin
cd /ptmp/Richard.Wobus/o/rwzs/com/output/dev/20121022
cd ..
pwd
#echo TEST TESTS output check disabled TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
#rc=0
#DHOU 03/09/2012
#/global/save/wx20rw/h/bin/hpss.put.output.day >/dev/null 2>&1
rc=$?
if (( rc == 0 )); then
  echo do not reset waitflag because rc=$rc
else
  echo reset waitflag because rc=$rc
  echo waitflag=`cat /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control/waitfile.t` before
  echo yes>/ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control/waitfile.t
  echo waitflag=`cat /ensemble/save/Richard.Wobus/WCOSS/rwzs/nwdev/control/waitfile.t` after
fi
echo `date` test output files end
