#!/bin/ksh
#
#BSUB -J zm2013020500100.130208162511
#BSUB -o /ptmp/Richard.Wobus/o/rwzm/com/output/dev/20130205/zm2013020500100.130208162511.o
#BSUB -e /ptmp/Richard.Wobus/o/rwzm/com/output/dev/20130205/zm2013020500100.130208162511.o
#BSUB -W 1:30
#BSUB -q "hpc_ibm" 
##BSUB -q "dev" 
#BSUB -L /bin/ksh
#
#
#BSUB -a poe
#BSUB -n 2100
#BSUB -R span[ptile=16]
#BSUB -x  

export OMP_NUM_THREADS=1
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_SHARED_MEMORY=no
export MEMORY_AFFINITY=core:1 

export total_tasks=2100
module load ics
module load ibmpe
#module load mpt
#module load adaptive
echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev begin
echo `date` env sort begin
env | sort
echo `date` env sort end

export envir=dev
export cyc=00
export cyc_fcst=00
export job=zm2013020500100
export RUN=gep20
export FORECAST_SEGMENT=hr
# export for development runs only begin
pwdsave=$(pwd)
echo $pwdsave
cd /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control
. /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control/setbase
. /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/parm/gefs.parm
cd 
export RUN_ENVIR=dev
export gefsmachine=wcoss
export gefsmpexec=mpirun.lsf
export jjj=100
export jjje=999
export yyyymmddcc=2013020500
export yyyymmddcce=2013020600
export yyyymmddccjjj=2013020500100
export yyyymmddccjjje=2013020600999
# export yyyymmddccc  #DHOU, 09/09/2010 ad this to facilitate job 000
# RLW disabled since the copy of initial conditions is moved into this script
#if (( jjj == 000 )); then
#  export yyyymmddccc=2013020500
#fi
export PDYp2=20130207
export PDYp1=20130206
export PDY=20130205
export PDYm1=20130204
export PDYm2=20130203
export PDYm3=20130202
export PDYm4=20130201
export PDYm5=20130131
export id=zm
export expid=rwzm
export basesource=/ensemble/save/Richard.Wobus/WCOSS/rwzm
export baseoutput=/ptmp/Richard.Wobus/o/rwzm
export baseinitarch=/global/mirror/Richard.Wobus/o/rwzm
export basetmp=/ptmp/Richard.Wobus/o/rwzm
export baseptmp=/ptmp/Richard.Wobus/o/rwzm
export basebin=/global/save/Richard.Wobus/s/rwzm/nwdev/control
export baselog=/ptmp/Richard.Wobus/o/rwzm
export basedgfs=/ensemble/noscrub/Richard.Wobus/o
export basedgens=/ptmp/Richard.Wobus/o
echo `date` env sort begin
env | sort
echo `date` env sort end
# export for development runs only end

pwdsave=`pwd`

echo `date` ./gefsrun 2013020500100 2013020600999 next submit for dev before begin

cd /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control
./gefsrun 2013020500100 2013020600999 nextbefore 2>&1
rc=$?
echo `date` ./gefsrun 2013020500100 2013020600999 nextbefore rc=$rc
cd $pwdsave
echo `date` ./gefsrun 2013020500100 2013020600999 next submit for dev before end

echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev run before

echo
ls -al /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev
echo

# CALL executable job script here
/ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev

echo
ls -al /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev
echo

echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev run after

echo `date` ./gefsrun  2013020500100 2013020600999 next submit for dev after begin

cd /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control
./gefsrun 2013020500100 2013020600999 nextafter 2>&1
rc=$?
echo `date` ./gefsrun 2013020500100 2013020600999 nextafter rc=$rc

cd $pwdsave
echo `date` ./gefsrun  2013020500100 2013020600999 next submit for dev after end

echo `date` /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/jobs/JGEFS_FORECAST.sms.dev end
echo `date` test output files begin
cd /ptmp/Richard.Wobus/o/rwzm/com/output/dev/20130205
cd ..
pwd
#echo TEST TESTS output check disabled TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
#rc=0
#DHOU 03/09/2012
#/global/save/wx20rw/h/bin/hpss.put.output.day >/dev/null 2>&1
rc=$?
if (( rc == 0 )); then
  echo do not reset waitflag because rc=$rc
else
  echo reset waitflag because rc=$rc
  echo waitflag=`cat /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control/waitfile.t` before
  echo yes>/ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control/waitfile.t
  echo waitflag=`cat /ensemble/save/Richard.Wobus/WCOSS/rwzm/nwdev/control/waitfile.t` after
fi
echo `date` test output files end
